.git
.idea
.turbo
node_modules
**/node_modules

.env
.env.*
!.env.example
!.env.*.example

dist
**/dist
build
**/build
.next
**/.next
out
**/out
coverage
**/coverage

npm-debug.log*
yarn-debug.log*
yarn-error.log*
pnpm-debug.log*
