const savedSnippets = {
  data: [
    {
      id: "2a06ba1d-3ee6-4dc1-a485-cf4e7b22f4eb",
      slug: "concat",
      topicSlug: "array-methods",
      title: "Implement Array.prototype.concat",
      language: "js",
      code: "Array.prototype.myConcat = function (...arrays) {\n  const result = [...this];\n\n  for (const array of arrays) {\n    if (Array.isArray(array)) {\n      result.push(...array);\n    } else {\n      result.push(array);\n    }\n  }\n\n  return result;\n};",
      createdAt: "2026-07-08T17:47:34.149Z",
      updatedAt: "2026-07-08T17:47:34.149Z",
    },
    {
      id: "af4084a5-7dfc-4e7b-86c6-108d3ce7b682",
      slug: "fill",
      topicSlug: "array-methods",
      title: "Implement Array.prototype.fill",
      language: "js",
      code: "Array.prototype.customFill = function (value, start = 0, end = this.length) {\n  if (start < 0) {\n    start = this.length + start;\n  }\n\n  if (end < 0) {\n    end = this.length + end;\n  }\n\n  for (let i = start; i < Math.min(end, this.length); i++) {\n    this[i] = value;\n  }\n\n  return this;\n};",
      createdAt: "2026-07-08T17:47:34.191Z",
      updatedAt: "2026-07-08T17:47:34.191Z",
    },
    {
      id: "c4dce4b3-1435-4d35-9384-d722ceae0000",
      slug: "pop",
      topicSlug: "array-methods",
      title: "Implement Array.prototype.pop",
      language: "js",
      code: "Array.prototype.customPop = function () {\n  const length = this.length;\n\n  if (length === 0) {\n    return undefined;\n  }\n\n  const lastElement = this[length - 1];\n  this.length = length - 1;\n\n  return lastElement;\n};",
      createdAt: "2026-07-08T17:47:34.245Z",
      updatedAt: "2026-07-08T17:47:34.245Z",
    },
    {
      id: "685e115c-ed27-40a2-85fe-194e102101a5",
      slug: "push",
      topicSlug: "array-methods",
      title: "Implement Array.prototype.push",
      language: "js",
      code: "Array.prototype.customPush = function () {\n  for (let i = 0; i < arguments.length; i++) {\n    this[this.length] = arguments[i];\n  }\n\n  return this.length;\n};",
      createdAt: "2026-07-08T17:47:34.277Z",
      updatedAt: "2026-07-08T17:47:34.277Z",
    },
    {
      id: "0f359057-08ed-4f8f-becc-c591e5c0fd6c",
      slug: "reverse",
      topicSlug: "array-methods",
      title: "Implement Array.prototype.reverse",
      language: "js",
      code: "Array.prototype.customReverse = function () {\n  const middle = Math.floor(this.length / 2);\n\n  for (let i = 0; i < middle; i++) {\n    const temp = this[i];\n    this[i] = this[this.length - 1 - i];\n    this[this.length - 1 - i] = temp;\n  }\n\n  return this;\n};",
      createdAt: "2026-07-08T17:47:34.323Z",
      updatedAt: "2026-07-08T17:47:34.323Z",
    },
    {
      id: "5e39e7ad-3c52-4bd0-b0c6-07e25fcdfa95",
      slug: "shift",
      topicSlug: "array-methods",
      title: "Implement Array.prototype.shift",
      language: "js",
      code: "Array.prototype.customShift = function () {\n  if (!this.length) return;\n\n  const firstElement = this[0];\n\n  for (let i = 0; i < this.length; i++) {\n    this[i] = this[i + 1];\n  }\n\n  this.length -= 1;\n\n  return firstElement;\n};",
      createdAt: "2026-07-08T17:47:34.356Z",
      updatedAt: "2026-07-08T17:47:34.356Z",
    },
    {
      id: "c55dbcec-9cad-43ab-858e-e65ff881f339",
      slug: "unshift",
      topicSlug: "array-methods",
      title: "Implement Array.prototype.unshift",
      language: "js",
      code: "Array.prototype.customUnshift = function (...elements) {\n  const originalLength = this.length;\n  const totalLength = elements.length + originalLength;\n\n  // Shift existing elements to the right\n  for (let i = originalLength - 1; i >= 0; i--) {\n    this[i + elements.length] = this[i];\n  }\n\n  // Add new elements at the beginning\n  for (let i = 0; i < elements.length; i++) {\n    this[i] = elements[i];\n  }\n\n  return totalLength; // Return the new length\n};",
      createdAt: "2026-07-08T17:47:34.384Z",
      updatedAt: "2026-07-08T17:47:34.384Z",
    },
    {
      id: "59b5106c-44a9-4c99-a2e4-d9804ee3374e",
      slug: "splice",
      topicSlug: "array-methods",
      title: "Implement Array.prototype.splice",
      language: "js",
      code: "Array.prototype.customSplice = function (\n  startIndex,\n  deleteCount,\n  ...itemsToAdd\n) {\n  const length = this.length;\n\n  // Handle negative indices\n  startIndex =\n    startIndex < 0\n      ? Math.max(length + startIndex, 0)\n      : Math.min(startIndex, length);\n\n  // If deleteCount is undefined, remove all elements starting from startIndex\n  if (deleteCount === undefined) {\n    deleteCount = length - startIndex;\n  } else {\n    // Normalize deleteCount\n    deleteCount = Math.max(0, Math.min(deleteCount, length - startIndex));\n  }\n\n  // Extract the array to be deleted\n  const splicedItems = this.slice(startIndex, startIndex + deleteCount);\n\n  // Create the resulting this by combining parts and items to add\n  const remainingItems = [\n    ...this.slice(0, startIndex),\n    ...itemsToAdd,\n    ...this.slice(startIndex + deleteCount),\n  ];\n\n  // Update the original array\n  this.length = 0; // Clear the this\n  for (let i = 0; i < remainingItems.length; i++) {\n    this[i] = remainingItems[i];\n  }\n\n  // Return the deleted items\n  return splicedItems;\n};",
      createdAt: "2026-07-08T17:47:34.412Z",
      updatedAt: "2026-07-08T17:47:34.412Z",
    },
    {
      id: "d6b16758-94e0-4f6d-9b7d-e0c608dde64a",
      slug: "filter",
      topicSlug: "array-methods",
      title: "Implement Array.prototype.filter",
      language: "js",
      code: "Array.prototype.myFilter = function (callback) {\n  const result = [];\n\n  for (let i = 0; i < this.length; i++) {\n    if (callback(this[i], i, this)) {\n      result.push(this[i]);\n    }\n  }\n\n  return result;\n};",
      createdAt: "2026-07-08T17:47:34.440Z",
      updatedAt: "2026-07-08T17:47:34.440Z",
    },
    {
      id: "7f578f70-abe4-4a85-a666-cd25f88911c4",
      slug: "flat",
      topicSlug: "array-methods",
      title: "Implement Array.prototype.flat",
      language: "js",
      code: "Array.prototype.customFlat = function (depth = 1) {\n  const result = [];\n\n  const flatten = (array, depth) => {\n    for (const item of array) {\n      if (Array.isArray(item) && depth > 0) {\n        flatten(item, depth - 1);\n      } else {\n        result.push(item);\n      }\n    }\n  };\n  flatten(this, depth);\n\n  return result;\n};",
      createdAt: "2026-07-08T17:47:34.468Z",
      updatedAt: "2026-07-08T17:47:34.468Z",
    },
    {
      id: "0e52477a-ffda-4487-b4f5-a9ede575cf40",
      slug: "flatmap",
      topicSlug: "array-methods",
      title: "Implement Array.prototype.flatMap",
      language: "js",
      code: "Array.prototype.customFlatMap = function (callback, thisArg) {\n  const result = [];\n\n  for (let i = 0; i < this.length; i++) {\n    const mapped = callback.call(thisArg, this[i], i, this);\n\n    if (Array.isArray(mapped)) {\n      result.push(...mapped); // Use spread operator for flattening\n    } else {\n      result.push(mapped);\n    }\n  }\n\n  return result;\n};",
      createdAt: "2026-07-08T17:47:34.497Z",
      updatedAt: "2026-07-08T17:47:34.497Z",
    },
    {
      id: "3947bfc9-3422-46af-a8ff-23d5181d7ef0",
      slug: "join",
      topicSlug: "array-methods",
      title: "Implement Array.prototype.join",
      language: "js",
      code: 'Array.prototype.customJoin = function (separator = ",") {\n  let result = "";\n\n  for (let i = 0; i < this.length; i++) {\n    if (i > 0) {\n      result += separator;\n    }\n\n    result += this[i];\n  }\n\n  return result;\n};',
      createdAt: "2026-07-08T17:47:34.527Z",
      updatedAt: "2026-07-08T17:47:34.527Z",
    },
    {
      id: "e1573c2b-f658-4cdf-982f-671453849768",
      slug: "map",
      topicSlug: "array-methods",
      title: "Implement Array.prototype.map",
      language: "js",
      code: 'Array.prototype.customMap = function (callbackFn) {\n  if (typeof callbackFn !== "function") {\n    throw new TypeError("Callback must be a function");\n  }\n\n  const arr = [];\n  for (let i = 0; i < this.length; i++) {\n    arr.push(callbackFn(this[i], i, this));\n  }\n\n  return arr;\n};',
      createdAt: "2026-07-08T17:47:34.556Z",
      updatedAt: "2026-07-08T17:47:34.556Z",
    },
    {
      id: "5fac89da-a848-44b0-bea1-ec462e98ac76",
      slug: "reduce",
      topicSlug: "array-methods",
      title: "Implement Array.prototype.reduce",
      language: "js",
      code: "Array.prototype.customReduce = function (callback, initialValue) {\n  let accumulator = initialValue !== undefined ? initialValue : this[0];\n\n  const startIndex = initialValue !== undefined ? 0 : 1;\n\n  for (let i = startIndex; i < this.length; i++) {\n    accumulator = callback(accumulator, this[i], i, this);\n  }\n\n  return accumulator;\n};",
      createdAt: "2026-07-08T17:47:34.585Z",
      updatedAt: "2026-07-08T17:47:34.585Z",
    },
    {
      id: "c36a85ee-626f-4442-9752-ed56e2e207ee",
      slug: "slice",
      topicSlug: "array-methods",
      title: "Implement Array.prototype.slice",
      language: "js",
      code: "Array.prototype.customSlice = function (start = 0, end) {\n  const length = this.length;\n  let endIndex = end || length;\n\n  if (start < 0) {\n    start = Math.max(length + start, 0);\n  }\n  if (endIndex < 0) {\n    endIndex = Math.max(length + endIndex, 0);\n  }\n\n  const result = [];\n\n  for (let i = start; i < endIndex && i < length; i++) {\n    result.push(this[i]);\n  }\n\n  return result;\n};",
      createdAt: "2026-07-08T17:47:34.614Z",
      updatedAt: "2026-07-08T17:47:34.614Z",
    },
    {
      id: "57b973f9-7eea-48a0-ad8c-5342a353756d",
      slug: "find",
      topicSlug: "array-methods",
      title: "Implement Array.prototype.find",
      language: "js",
      code: "Array.prototype.customFind = function (callback) {\n  for (let i = 0; i < this.length; i++) {\n    if (callback(this[i])) {\n      return this[i];\n    }\n  }\n};",
      createdAt: "2026-07-08T17:47:34.642Z",
      updatedAt: "2026-07-08T17:47:34.642Z",
    },
    {
      id: "07051a5d-5d36-4481-b8e7-b542a2bac766",
      slug: "findlast",
      topicSlug: "array-methods",
      title: "Implement Array.prototype.findLast",
      language: "js",
      code: "Array.prototype.customFindLast = function (callback) {\n  for (let i = this.length; i >= 0; i--) {\n    if (callback(this[i])) {\n      return this[i];\n    }\n  }\n};",
      createdAt: "2026-07-08T17:47:34.670Z",
      updatedAt: "2026-07-08T17:47:34.670Z",
    },
    {
      id: "6009409a-7b31-4933-934b-de0c4b9a5ba2",
      slug: "at",
      topicSlug: "array-methods",
      title: "Implement Array.prototype.at",
      language: "js",
      code: "Array.prototype.customAt = function (index) {\n  if (index < 0) {\n    index = this.length + index;\n  }\n\n  return this[index];\n};",
      createdAt: "2026-07-08T17:47:34.700Z",
      updatedAt: "2026-07-08T17:47:34.700Z",
    },
    {
      id: "6797db4c-b801-421c-8c83-e0ba82991076",
      slug: "every",
      topicSlug: "array-methods",
      title: "Implement Array.prototype.every",
      language: "js",
      code: "Array.prototype.customEvery = function (callback) {\n  for (let i = 0; i < this.length; i++) {\n    if (!callback(this[i], i)) {\n      return false;\n    }\n  }\n\n  return true;\n};",
      createdAt: "2026-07-08T17:47:34.731Z",
      updatedAt: "2026-07-08T17:47:34.731Z",
    },
    {
      id: "38479e07-cdaf-47ef-9c9b-a669331de990",
      slug: "includes",
      topicSlug: "array-methods",
      title: "Implement Array.prototype.includes",
      language: "js",
      code: 'function sameValueZero(x, y) {\n  return (\n    x === y ||\n    (typeof x === "number" && typeof y === "number" && x !== x && y !== y)\n  );\n}\n\nArray.prototype.customIncludes = function (searchElement, fromIndex = 0) {\n  const length = this.length;\n\n  if (length === 0) {\n    return false;\n  }\n\n  if (fromIndex < 0) {\n    fromIndex = Math.max(length + fromIndex, 0);\n  }\n\n  for (let i = fromIndex; i < length; i++) {\n    if (sameValueZero(this[i], searchElement)) {\n      return true;\n    }\n  }\n\n  return false;\n};',
      createdAt: "2026-07-08T17:47:34.765Z",
      updatedAt: "2026-07-08T17:47:34.765Z",
    },
    {
      id: "9797e6bf-4c33-4c61-b342-e375dd5f944f",
      slug: "some",
      topicSlug: "array-methods",
      title: "Implement Array.prototype.some",
      language: "js",
      code: "Array.prototype.customSome = function (callback) {\n  for (let i = 0; i < this.length; i++) {\n    if (callback(this[i], i, this)) {\n      return true;\n    }\n  }\n\n  return false;\n};",
      createdAt: "2026-07-08T17:47:34.797Z",
      updatedAt: "2026-07-08T17:47:34.797Z",
    },
    {
      id: "d4538e0c-6941-4cca-bf68-3090bdbbb50c",
      slug: "composition",
      topicSlug: "composition-vs-inheritance",
      title: "Function Composition Pipeline",
      language: "js",
      code: "const dateFunc = () => new Date();\nconst textFunc = (date) => date.toDateString();\nconst labelFunc = (text) => `Today ${text}`;\nconst showLabelFunc = (label) => console.log(label);\n\nconst date = dateFunc();\nconst text = textFunc(date);\nconst label = labelFunc(text);\nshowLabelFunc(label);\n\nfunction pipe(...steps) {\n  return function runSteps() {\n    let result;\n    for (let i = 0; i < steps.length; i++) {\n      let step = steps[i];\n      result = step(result);\n    }\n    return result;\n  };\n}\n\nconst showDateLabel = pipe(dateFunc, textFunc, labelFunc, showLabelFunc);\nshowDateLabel();",
      createdAt: "2026-07-08T17:47:34.826Z",
      updatedAt: "2026-07-08T17:47:34.826Z",
    },
    {
      id: "7cc44719-cf31-4dda-9fde-b21a239ddd0b",
      slug: "this",
      topicSlug: "core-concepts",
      title: "thisArg in Array Callbacks",
      language: "js",
      code: '"use strict";\n\nArray.prototype.customFilter = function (callback, thisArg) {\n  let result = [];\n\n  for (let i = 0; i < this.length; i++) {\n    if (callback.call(thisArg, this[i], i, this)) {\n      result.push(this[i]);\n    }\n  }\n\n  return result;\n};\n\nArray.prototype.customFilterNoThis = function (callback) {\n  let result = [];\n\n  for (let i = 0; i < this.length; i++) {\n    if (callback(this[i], i, this)) {\n      result.push(this[i]);\n    }\n  }\n\n  return result;\n};\n\nconst army = {\n  minAge: 18,\n  maxAge: 27,\n  canJoin(user) {\n    return user.age >= this.minAge && user.age < this.maxAge;\n  },\n};\n\nconst users = [{ age: 16 }, { age: 20 }, { age: 23 }, { age: 30 }];\n\nconst soldiers2 = users.customFilterNoThis((user) => army.canJoin(user));\nconst soldiers3 = users.customFilter(army.canJoin, army);\n\nconsole.log(soldiers2);\nconsole.log(soldiers3);',
      createdAt: "2026-07-08T17:47:34.859Z",
      updatedAt: "2026-07-08T17:47:34.859Z",
    },
    {
      id: "cf1a860b-46c2-4fd4-93bd-1685d2c306c6",
      slug: "object-method-this",
      topicSlug: "core-concepts",
      title: "Broken Object Method Receiver",
      language: "js",
      code: 'let user = {\n  name: "John",\n  sayHi() {\n    console.log(user.name);\n  },\n};\n\nconst admin = user;\nuser = null;\n\nadmin.sayHi();',
      createdAt: "2026-07-08T17:47:34.894Z",
      updatedAt: "2026-07-08T17:47:34.894Z",
    },
    {
      id: "a7e7a3d2-40f9-42c0-ac4e-05b06c179213",
      slug: "object-method-this-fix",
      topicSlug: "core-concepts",
      title: "Object Method Receiver with this",
      language: "js",
      code: 'let user = {\n  name: "John",\n  sayHi() {\n    console.log(this.name);\n  },\n};\n\nconst admin = user;\nuser = null;\n\nadmin.sayHi();',
      createdAt: "2026-07-08T17:47:34.922Z",
      updatedAt: "2026-07-08T17:47:34.922Z",
    },
    {
      id: "f021b91b-3bc6-4c58-9a9c-48745461ac38",
      slug: "object-literal-this",
      topicSlug: "core-concepts",
      title: "Object Literals and this Binding",
      language: "js",
      code: 'function makeUser() {\n  return {\n    name: "John",\n    ref: this,\n  };\n}\n\nconst user = makeUser();\nconsole.log(user.ref?.name); \n\nfunction makeUserWithMethod() {\n  return {\n    name: "John",\n    ref() {\n      return this;\n    },\n  };\n}\n\nconst user2 = makeUserWithMethod();\nconsole.log(user2.ref().name);',
      createdAt: "2026-07-08T17:47:34.948Z",
      updatedAt: "2026-07-08T17:47:34.948Z",
    },
    {
      id: "e9fc77ef-da9f-431c-b0ed-2d158ba3569b",
      slug: "method-chaining",
      topicSlug: "core-concepts",
      title: "Method Chaining with this",
      language: "js",
      code: "const ladder = {\n  step: 0,\n  up() {\n    this.step++;\n    return this;\n  },\n  down() {\n    this.step--;\n    return this;\n  },\n  showStep() {\n    console.log(this.step);\n    return this;\n  },\n};\n\nladder.up().up().down().showStep().down().showStep();",
      createdAt: "2026-07-08T17:47:34.976Z",
      updatedAt: "2026-07-08T17:47:34.976Z",
    },
    {
      id: "e91830e5-de05-45d8-b190-212a49ed7843",
      slug: "for-vs-while",
      topicSlug: "core-concepts",
      title: "Pre-Increment vs Post-Increment in Loops",
      language: "js",
      code: "let i = 0;\nwhile (++i < 3) console.log(i);\n\nlet i2 = 0;\nwhile (i2++ < 3) console.log(i2);\n\nfor (let i = 0; i < 3; i++) console.log(i);\n\nfor (let i = 0; i < 3; ++i) console.log(i);",
      createdAt: "2026-07-08T17:47:35.004Z",
      updatedAt: "2026-07-08T17:47:35.004Z",
    },
    {
      id: "e81fa2eb-e9a4-4ab1-ae25-7fb8817958c7",
      slug: "bind",
      topicSlug: "core-concepts",
      title: "Lost Method Receiver in setTimeout",
      language: "js",
      code: 'const user = {\n  firstName: "John",\n  sayHi() {\n    console.log(`Hello, ${this.firstName}!`);\n  },\n};\n\nuser.sayHi();\nsetTimeout(user.sayHi, 0);',
      createdAt: "2026-07-08T17:47:35.035Z",
      updatedAt: "2026-07-08T17:47:35.035Z",
    },
    {
      id: "e7c81592-c974-418d-bfa4-7ac9b8bea0d4",
      slug: "call-and-arrows",
      topicSlug: "core-concepts",
      title: "call with Regular and Arrow Functions",
      language: "js",
      code: "const obj = {\n  value: 25,\n  regularMethod() {\n    return this.value;\n  },\n  arrowMethod: () => {\n    return this?.value;\n  },\n};\n\nconst anotherObj = {\n  value: 50,\n};",
      createdAt: "2026-07-08T17:47:35.063Z",
      updatedAt: "2026-07-08T17:47:35.063Z",
    },
    {
      id: "f9c43ca8-b61b-4321-8584-011c14e92486",
      slug: "object-create",
      topicSlug: "core-concepts",
      title: "Prototype Inheritance with Object.create",
      language: "js",
      code: 'const vehicle = {\n  getInfo() {\n    console.log(`${this.model} was made in ${this.year}`);\n  },\n};\n\nconst myCar = Object.create(vehicle);\nmyCar.model = "BMW";\nmyCar.year = 2010;\n\nmyCar.getInfo();',
      createdAt: "2026-07-08T17:47:35.092Z",
      updatedAt: "2026-07-08T17:47:35.092Z",
    },
    {
      id: "bd24d6c1-0561-4132-b156-65768814335a",
      slug: "async-generator",
      topicSlug: "core-concepts",
      title: "Async Generator Sequence",
      language: "js",
      code: "async function* generateSequence(start, end) {\n  for (let i = start; i <= end; i++) {\n    await new Promise((resolve) => setTimeout(resolve, 1000));\n    yield i;\n  }\n}\n\nconst timer = async (callback) => {\n  const generator = generateSequence(1, 5);\n  for await (let value of generator) {\n    callback(value);\n  }\n};",
      createdAt: "2026-07-08T17:47:35.151Z",
      updatedAt: "2026-07-08T17:47:35.151Z",
    },
    {
      id: "d4d50575-2588-4c51-9b5d-a18ad0f62354",
      slug: "function-stack",
      topicSlug: "core-concepts",
      title: "Recursive Call Stack Order",
      language: "js",
      code: "function foo(i) {\n  if (i < 0) {\n    return;\n  }\n  console.log(`begin: ${i}`);\n  foo(i - 1);\n  console.log(`end: ${i}`);\n}",
      createdAt: "2026-07-08T17:47:35.186Z",
      updatedAt: "2026-07-08T17:47:35.186Z",
    },
    {
      id: "b7ab9391-3c86-4e1f-b803-f228b3bf6f65",
      slug: "lexical-environment-scope-fixed",
      topicSlug: "core-concepts",
      title: "Closure Capture in Loops",
      language: "js",
      code: "function makeArmy() {\n  const shooters = [];\n\n  let i = 0;\n  while (i < 10) {\n    let j = i;\n    const shooter = function () {\n      return j;\n    };\n    shooters.push(shooter);\n    i++;\n  }\n\n  return shooters;\n}\n\nconst army = makeArmy();\n\nconsole.log(army[0]());\nconsole.log(army[1]());\nconsole.log(army[5]());",
      createdAt: "2026-07-08T17:47:35.215Z",
      updatedAt: "2026-07-08T17:47:35.215Z",
    },
    {
      id: "70528f36-0bc1-4c00-8270-ef6b1bfcbbcc",
      slug: "lexical-environment-scope-broken",
      topicSlug: "core-concepts",
      title: "Broken Closure Scope in Loops",
      language: "js",
      code: "function makeArmy() {\n  const shooters = [];\n\n  let i = 0;\n  while (i < 10) {\n    const shooter = function () {\n      return i;\n    };\n    shooters.push(shooter);\n    i++;\n  }\n\n  return shooters;\n}\n\nconst army = makeArmy();\n\nconsole.log(army[0]());\nconsole.log(army[1]());\nconsole.log(army[5]());",
      createdAt: "2026-07-08T17:47:35.244Z",
      updatedAt: "2026-07-08T17:47:35.244Z",
    },
    {
      id: "f3f74a08-3c13-4645-b8d3-2167528a3963",
      slug: "output-every-second",
      topicSlug: "debounce-throttle",
      title: "Interval-Based Number Printer",
      language: "js",
      code: "function printNumbers(from, to) {\n  let current = from;\n  let timerId;\n\n  function go() {\n    console.log(current);\n    if (current === to) {\n      clearInterval(timerId);\n    }\n    current++;\n  }\n\n  go();\n  timerId = setInterval(go, 1000);\n}\n\nprintNumbers(5, 10);",
      createdAt: "2026-07-08T17:47:35.275Z",
      updatedAt: "2026-07-08T17:47:35.275Z",
    },
    {
      id: "8ecb0a9d-d9e9-4a3b-861e-14539b66dab3",
      slug: "output-every-second-2",
      topicSlug: "debounce-throttle",
      title: "Timeout-Based Number Printer",
      language: "js",
      code: "function printNumbers(from, to) {\n  let current = from;\n\n  function go() {\n    console.log(current);\n    if (current < to) {\n      setTimeout(go, 1000);\n    }\n    current++;\n  }\n\n  go();\n}\n\nprintNumbers(5, 10);",
      createdAt: "2026-07-08T17:47:35.305Z",
      updatedAt: "2026-07-08T17:47:35.305Z",
    },
    {
      id: "3cea4ad2-2fba-4d7f-b54d-7bfbe90e15a6",
      slug: "debounce",
      topicSlug: "debounce-throttle",
      title: "Implement debounce",
      language: "js",
      code: 'function debounce(func, ms) {\n  let timeout;\n\n  return function (...args) {\n    clearTimeout(timeout);\n    timeout = setTimeout(() => func.apply(this, args), ms);\n  };\n}\n\nconst timeLoggedConsoleLog = (...args) => {\n  console.log(`Logged after ${Date.now() - startTime} ms:`, ...args);\n};\n\nconst startTime = Date.now();\nconst f = debounce(timeLoggedConsoleLog, 500);\n\nf("a");\nsetTimeout(() => f("b"), 200);\nsetTimeout(() => f("c"), 600);\nsetTimeout(() => f("d"), 600);\nsetTimeout(() => f("e"), 600); // Logged after 1118 ms: e',
      createdAt: "2026-07-08T17:47:35.333Z",
      updatedAt: "2026-07-08T17:47:35.333Z",
    },
    {
      id: "a5da8d8d-aa19-4222-934a-8ad8e9f7d0cf",
      slug: "throttle",
      topicSlug: "debounce-throttle",
      title: "Implement throttle",
      language: "js",
      code: "function throttle(fn, limit) {\n  let inThrottle;\n\n  return function (...args) {\n    if (inThrottle) return;\n    fn.apply(this, args);\n    inThrottle = true;\n    setTimeout(() => (inThrottle = false), limit);\n  };\n}\n\nconst timeLoggedConsoleLog = (...args) => {\n  console.log(`Logged after ${Date.now() - startTime} ms:`, ...args);\n};\n\nconst startTime = Date.now();\nconst f = throttle(timeLoggedConsoleLog, 500);",
      createdAt: "2026-07-08T17:47:35.361Z",
      updatedAt: "2026-07-08T17:47:35.361Z",
    },
    {
      id: "86e435da-37f1-444e-91b2-598d63d9637c",
      slug: "promise-all-and-the-event-loop",
      topicSlug: "event-loop",
      title: "Promise.all and Event Loop Timing",
      language: "js",
      code: 'const promise1 = Promise.resolve(3);\nconst promise2 = new Promise((resolve, reject) => {\n  setTimeout(resolve, 1000, "foo");\n});\nconst promise3 = 42;\n\nPromise.all([promise1, promise2, promise3]).then((values) => {\n  console.log({ values });\n});\n\n// Using setTimeout, we can execute code after the queue is empty\nsetTimeout(() => {\n  console.log("the queue is now empty");\n});\n\nconst p3 = Promise.all([]); // Will be immediately resolved\nconst p4 = Promise.all([1337, "hi"]);\n\n// Non-promise values are ignored, but the evaluation is done asynchronously\nconsole.log({ p3 });\nconsole.log({ p4 });\n\nsetTimeout(() => {\n  console.log({ p4 });\n});\n\nPromise.all([promise1, promise2, promise3]).then((values) => {\n  console.log({ values2: values });\n});\n\nconst promise4 = Promise.resolve(3);\nconst promise5 = 42;\n\nPromise.all([promise4, promise5]).then((values) => {\n  console.log({ values3: values });\n});',
      createdAt: "2026-07-08T17:47:35.389Z",
      updatedAt: "2026-07-08T17:47:35.389Z",
    },
    {
      id: "d770bbff-2d9e-490d-8a23-483ad190b10b",
      slug: "promise-chaining-and-microtask-queue-order",
      topicSlug: "event-loop",
      title: "Promise Chain Microtask Order",
      language: "js",
      code: "const promise1 = Promise.resolve();\nconst promise2 = Promise.resolve();\n\npromise1.then(() => console.log(1)).then(() => console.log(2));\npromise2.then(() => console.log(3)).then(() => console.log(4));",
      createdAt: "2026-07-08T17:47:35.422Z",
      updatedAt: "2026-07-08T17:47:35.422Z",
    },
    {
      id: "7881ac86-e0cd-4b8b-b114-6fa52c2c7437",
      slug: "let-in-loops-with-settimeout",
      topicSlug: "event-loop",
      title: "let in Loops with setTimeout",
      language: "js",
      code: "for (let i = 0; i < 4; i++) {\n  setTimeout(() => {\n    console.log(i);\n  }, 1000);\n}",
      createdAt: "2026-07-08T17:47:35.450Z",
      updatedAt: "2026-07-08T17:47:35.450Z",
    },
    {
      id: "4aa3db11-2148-4c6f-9d75-570fc6c5f2ec",
      slug: "promise-lifecycle-and-event-loop-timing",
      topicSlug: "event-loop",
      title: "Promise Lifecycle Timing",
      language: "js",
      code: 'const promise = new Promise((resolve, reject) => {\n  console.log("Promise callback");\n  resolve("resolved");\n  console.log("Promise callback end");\n}).then((result) => {\n  console.log("Promise callback (.then)", result);\n});\n\nsetTimeout(() => {\n  console.log("event-loop cycle: Promise (fulfilled)", promise);\n}, 0);\n\nconsole.log("Promise (pending)", promise);',
      createdAt: "2026-07-08T17:47:35.480Z",
      updatedAt: "2026-07-08T17:47:35.480Z",
    },
    {
      id: "e05d4397-a43f-4061-b48b-d800c28ce6e2",
      slug: "async-function-and-timer-execution-order",
      topicSlug: "event-loop",
      title: "Async Function and Timer Ordering",
      language: "js",
      code: 'async function run() {\n  console.log("run async");\n  setTimeout(() => {\n    console.log("run timeout");\n  }, 0);\n}\n\nsetTimeout(() => {\n  console.log("timeout");\n}, 0);\n\n// await or not, same result\nawait run();\n\nconsole.log("script");',
      createdAt: "2026-07-08T17:47:35.509Z",
      updatedAt: "2026-07-08T17:47:35.509Z",
    },
    {
      id: "16c3f529-d2ca-42f5-bc8b-32c91edbd50b",
      slug: "blocking-the-event-loop-with-a-while-loop",
      topicSlug: "event-loop",
      title: "Blocking the Event Loop with a While Loop",
      language: "js",
      code: 'const seconds = new Date().getTime() / 1000;\n\nsetTimeout(() => {\n  // prints out "2", meaning that the callback is not called immediately after 500 milliseconds.\n  console.log(`Ran after ${new Date().getTime() / 1000 - seconds} seconds`);\n}, 500);\n\nwhile (true) {\n  if (new Date().getTime() / 1000 - seconds >= 2) {\n    console.log("Good, looped for 2 seconds");\n    break;\n  }\n}',
      createdAt: "2026-07-08T17:47:35.537Z",
      updatedAt: "2026-07-08T17:47:35.537Z",
    },
    {
      id: "61557457-4b82-46ab-a1cf-f8b5d79bb1ff",
      slug: "script-microtasks-and-macrotasks-in-execution-order",
      topicSlug: "event-loop",
      title: "Script, Microtask, and Macrotask Order",
      language: "js",
      code: 'console.log("Script start");\n\nsetTimeout(() => {\n  console.log("setTimeout");\n}, 0);\n\nPromise.resolve()\n  .then(() => {\n    console.log("Promise 1");\n  })\n  .then(() => {\n    console.log("Promise 2");\n  });\n\nconsole.log("Script end");\n\nconst promise1 = new Promise((resolve, reject) => {\n  console.log("Promise constructor");\n  resolve();\n}).then(() => {\n  console.log("Promise constructor resolve");\n});\n\nqueueMicrotask(() => {\n  console.log("Microtask queue");\n});\n\nconsole.log("After Promise constructor");',
      createdAt: "2026-07-08T17:47:35.564Z",
      updatedAt: "2026-07-08T17:47:35.564Z",
    },
    {
      id: "92a13335-dd7c-45c8-934e-48dc0b0be726",
      slug: "blocking-inside-async-callbacks",
      topicSlug: "event-loop",
      title: "Blocking Work Inside Async Callbacks",
      language: "js",
      code: 'function longRunningTask() {\n  console.log("Start Long-Running Task");\n\n  const startTime = Date.now();\n  while (Date.now() - startTime < 2000) {\n    // Simulate a long-running task (2 seconds)\n  }\n\n  console.log("Long-Running Task Completed");\n}\n\nfunction simulateNonBlocking() {\n  console.log("Start");\n\n  setTimeout(() => {\n    console.log("Non-blocking Operation");\n    longRunningTask();\n  }, 0);\n\n  console.log("End");\n}\n\nsimulateNonBlocking();',
      createdAt: "2026-07-08T17:47:35.592Z",
      updatedAt: "2026-07-08T17:47:35.592Z",
    },
    {
      id: "38f8a1d0-3044-4e30-9e77-a2991329ed04",
      slug: "nested-microtasks-in-macrotasks",
      topicSlug: "event-loop",
      title: "Nested Microtasks Inside Macrotasks",
      language: "js",
      code: 'console.log("Start");\n\nsetTimeout(() => {\n  console.log("setTimeout 1");\n  Promise.resolve().then(() => {\n    console.log("Promise inside setTimeout 1");\n  });\n}, 0);\n\nsetTimeout(() => {\n  console.log("setTimeout 2");\n}, 0);\n\nPromise.resolve()\n  .then(() => {\n    console.log("Promise 1");\n  })\n  .then(() => {\n    console.log("Promise 2");\n  });\n\nconsole.log("End");',
      createdAt: "2026-07-08T17:47:35.619Z",
      updatedAt: "2026-07-08T17:47:35.619Z",
    },
    {
      id: "928cc327-b67a-4e16-bdca-1243e654d020",
      slug: "requestanimationframe-and-task-ordering",
      topicSlug: "event-loop",
      title: "requestAnimationFrame and Task Ordering",
      language: "js",
      code: 'console.log("1");\n\nsetTimeout(function () {\n  console.log("2");\n\n  Promise.resolve().then(function () {\n    console.log("3");\n  });\n}, 0);\n\nPromise.resolve().then(function () {\n  console.log("4");\n\n  setTimeout(function () {\n    console.log("5");\n  }, 0);\n});\n\nrequestAnimationFrame(function () {\n  console.log("7");\n});\n\nconsole.log("6");',
      createdAt: "2026-07-08T17:47:35.649Z",
      updatedAt: "2026-07-08T17:47:35.649Z",
    },
    {
      id: "f7b47d7a-92f5-4512-9c81-b645f8f78538",
      slug: "has-path-dfs",
      topicSlug: "graph-traversal",
      title: "Directed Graph Path Search with DFS",
      language: "ts",
      code: "type Graph = Record<string, string[]>;\n\n// Depth-First Search\nconst hasPath = (graph: Graph, src: string, dst: string): boolean => {\n  if (src === dst) return true;\n\n  for (const neighbor of graph[src]) {\n    if (hasPath(graph, neighbor, dst)) {\n      return true;\n    }\n  }\n\n  return false;\n};",
      createdAt: "2026-07-08T17:47:35.678Z",
      updatedAt: "2026-07-08T17:47:35.678Z",
    },
    {
      id: "0b0589f7-7c80-430e-9079-baadd189a967",
      slug: "has-path-bfs",
      topicSlug: "graph-traversal",
      title: "Directed Graph Path Search with BFS",
      language: "ts",
      code: "type Graph = Record<string, string[]>;\n\nconst hasPath = (\n  graph: Graph,\n  src: string,\n  dst: string,\n): boolean => {\n  const queue: string[] = [src];\n\n  while (queue.length) {\n    const current = queue.shift();\n    if (current === dst) return true;\n\n    if (current && graph[current]) {\n      for (const neighbor of graph[current]) {\n        queue.push(neighbor);\n      }\n    }\n  }\n\n  return false;\n};",
      createdAt: "2026-07-08T17:47:35.706Z",
      updatedAt: "2026-07-08T17:47:35.706Z",
    },
    {
      id: "db88a53f-3adf-4823-adfe-3a0f731b4a5c",
      slug: "undirected-path",
      topicSlug: "graph-traversal",
      title: "Undirected Graph Path Search",
      language: "ts",
      code: "const undirectedPath = (\n  edges: [string, string][],\n  nodeA: string,\n  nodeB: string,\n): boolean => {\n  const graph = buildGraph(edges);\n  return hasPath(graph, nodeA, nodeB, new Set());\n};\n\nconst buildGraph = (edges: [string, string][]) => {\n  const graph: Record<string, string[]> = {};\n\n  for (const [a, b] of edges) {\n    if (!(a in graph)) graph[a] = [];\n    if (!(b in graph)) graph[b] = [];\n    graph[a].push(b);\n    graph[b].push(a);\n  }\n\n  return graph;\n};\n\nconst hasPath = (\n  graph: Record<string, string[]>,\n  src: string,\n  dst: string,\n  visited: Set<string>,\n): boolean => {\n  if (src === dst) return true;\n  if (visited.has(src)) return false;\n  visited.add(src);\n\n  for (const neighbor of graph[src]) {\n    if (hasPath(graph, neighbor, dst, visited)) {\n      return true;\n    }\n  }\n\n  return false;\n};",
      createdAt: "2026-07-08T17:47:35.734Z",
      updatedAt: "2026-07-08T17:47:35.734Z",
    },
    {
      id: "696af8f0-f026-4e5f-9c0e-af2d54eeb775",
      slug: "keyby",
      topicSlug: "lodash",
      title: "Implement keyBy",
      language: "js",
      code: 'function keyBy(collection, iteratee) {\n  const result = {};\n\n  for (const item of collection) {\n    const key =\n      typeof iteratee === "function" ? iteratee(item) : item[iteratee];\n    result[key] = item;\n  }\n\n  return result;\n}',
      createdAt: "2026-07-08T17:47:35.769Z",
      updatedAt: "2026-07-08T17:47:35.769Z",
    },
    {
      id: "4dd5d6aa-a36d-4ee1-b58a-6c6e1d4b0e8c",
      slug: "omit",
      topicSlug: "lodash",
      title: "Implement omit",
      language: "js",
      code: "function omit(obj, keys) {\n  const result = { ...obj };\n\n  if (!Array.isArray(keys)) {\n    delete result[keys];\n    return result;\n  }\n\n  for (const key of keys) {\n    delete result[key];\n  }\n\n  return result;\n}",
      createdAt: "2026-07-08T17:47:35.796Z",
      updatedAt: "2026-07-08T17:47:35.796Z",
    },
    {
      id: "94f1971f-94e5-43bb-bb8f-43dcbb67d2bd",
      slug: "orderby",
      topicSlug: "lodash",
      title: "Implement orderBy",
      language: "js",
      code: 'function orderBy(array, property, order = "asc") {\n  const multiplier = order === "asc" ? 1 : -1;\n  const copy = [...array];\n\n  return copy.sort((a, b) => {\n    if (a[property] < b[property]) return -1 * multiplier;\n    if (a[property] > b[property]) return 1 * multiplier;\n    return 0;\n  });\n}',
      createdAt: "2026-07-08T17:47:35.832Z",
      updatedAt: "2026-07-08T17:47:35.832Z",
    },
    {
      id: "168b9458-41cf-4779-b4c3-bd6bed6b3b50",
      slug: "pick",
      topicSlug: "lodash",
      title: "Implement pick",
      language: "js",
      code: 'function pick(obj, keys) {\n  if (typeof keys === "string") {\n    return obj[keys] !== undefined ? { [keys]: obj[keys] } : {};\n  }\n\n  return (Array.isArray(keys) ? keys : []).reduce((result, key) => {\n    if (key in obj) {\n      result[key] = obj[key];\n    }\n    return result;\n  }, {});\n}',
      createdAt: "2026-07-08T17:47:35.864Z",
      updatedAt: "2026-07-08T17:47:35.864Z",
    },
    {
      id: "b310ec38-e517-4c52-acd5-f91f1b9196fa",
      slug: "curry",
      topicSlug: "lodash",
      title: "Implement curry",
      language: "js",
      code: "function curry(fn) {\n  return function curried(...args) {\n    if (args.length >= fn.length) {\n      return fn(...args);\n    } else {\n      return (...nextArgs) => curried(...args, ...nextArgs);\n    }\n  };\n}",
      createdAt: "2026-07-08T17:47:35.888Z",
      updatedAt: "2026-07-08T17:47:35.888Z",
    },
    {
      id: "63109132-883e-47b3-8d68-b66c85642269",
      slug: "difference",
      topicSlug: "lodash",
      title: "Implement difference",
      language: "js",
      code: "const findDifference = function (arr1, arr2) {\n  const set1 = new Set(arr1);\n  const set2 = new Set(arr2);\n\n  const diffLeft = [];\n  const diffRight = [];\n\n  for (const item of set1) {\n    if (!set2.has(item)) diffLeft.push(item);\n  }\n\n  for (const item of set2) {\n    if (!set1.has(item)) diffRight.push(item);\n  }\n\n  return [diffLeft, diffRight];\n};",
      createdAt: "2026-07-08T17:47:35.914Z",
      updatedAt: "2026-07-08T17:47:35.914Z",
    },
    {
      id: "4123a3b9-12c2-46fa-87cb-cd3b442c9bba",
      slug: "differenceby",
      topicSlug: "lodash",
      title: "Implement differenceBy",
      language: "js",
      code: "const differenceBy = (arr1, arr2, key) => {\n  const set2 = new Set(arr2.map((item) => item[key]));\n  const set1 = new Set(arr1.map((item) => item[key]));\n\n  const diffLeft = [];\n  const diffRight = [];\n\n  for (const item of arr1) {\n    if (!set2.has(item[key])) {\n      diffLeft.push(item);\n    }\n  }\n\n  for (const item of arr2) {\n    if (!set1.has(item[key])) {\n      diffRight.push(item);\n    }\n  }\n\n  return [diffLeft, diffRight];\n};",
      createdAt: "2026-07-08T17:47:35.940Z",
      updatedAt: "2026-07-08T17:47:35.940Z",
    },
    {
      id: "f94bd2a2-bd9c-485d-928a-4fb745128ab1",
      slug: "intersection",
      topicSlug: "lodash",
      title: "Implement intersection",
      language: "js",
      code: "const intersection = function (nums1, nums2) {\n  const set1 = new Set(nums1);\n  const set2 = new Set(nums2);\n  const result = [];\n\n  for (const nums of set2) {\n    if (set1.has(nums)) {\n      result.push(nums);\n    }\n  }\n\n  return result;\n};",
      createdAt: "2026-07-08T17:47:35.967Z",
      updatedAt: "2026-07-08T17:47:35.967Z",
    },
    {
      id: "b1b57911-b68d-4fc8-837d-f9cc33ecb5c9",
      slug: "union",
      topicSlug: "lodash",
      title: "Implement union",
      language: "js",
      code: "const union = (...arrays) => {\n  return Array.from(new Set([].concat(...arrays)));\n};",
      createdAt: "2026-07-08T17:47:35.994Z",
      updatedAt: "2026-07-08T17:47:35.994Z",
    },
    {
      id: "f0da9141-cd18-4af2-9d86-99ee75233313",
      slug: "object-groupby",
      topicSlug: "map-and-set",
      title: "Implement Object.groupBy",
      language: "js",
      code: "const groupBy = (arr, callback) => {\n  return arr.reduce((acc = {}, item) => {\n    const key = callback(item);\n    if (!acc[key]) acc[key] = [];\n    acc[key].push(item);\n\n    return acc;\n  }, {});\n};",
      createdAt: "2026-07-08T17:47:36.023Z",
      updatedAt: "2026-07-08T17:47:36.023Z",
    },
    {
      id: "d1b82fd7-ec84-4047-a662-0fd55113a01d",
      slug: "promise-all",
      topicSlug: "promises",
      title: "Implement Promise.all",
      language: "js",
      code: 'function myPromiseAll(promises) {\n  return new Promise((resolve, reject) => {\n    if (!Array.isArray(promises)) {\n      return reject(new TypeError("Argument must be an array"));\n    }\n\n    const results = [];\n    let completedPromises = 0;\n\n    for (let index = 0; index < promises.length; index++) {\n      Promise.resolve(promises[index])\n        .then((value) => {\n          results[index] = value;\n          console.log(value);\n          completedPromises += 1;\n          if (completedPromises === promises.length) {\n            resolve(results);\n          }\n        })\n        .catch(reject);\n    }\n\n    if (promises.length === 0) {\n      resolve([]);\n    }\n  });\n}\n\nconst promise1 = new Promise((resolve, reject) => {\n  setTimeout(resolve, 3000, "first");\n});\nconst promise2 = new Promise((resolve, reject) => {\n  setTimeout(resolve, 1000, "second");\n});\nconst promise3 = new Promise((resolve, reject) => {\n  setTimeout(resolve, 5000, "third");\n});\n\nmyPromiseAll([promise1, promise2, promise3]).then((values) => {\n  console.log(values);\n});',
      createdAt: "2026-07-08T17:47:36.066Z",
      updatedAt: "2026-07-08T17:47:36.066Z",
    },
    {
      id: "da4c4ef3-9500-41f6-aed6-df3f10f9ff2b",
      slug: "promise-allsettled",
      topicSlug: "promises",
      title: "Implement Promise.allSettled",
      language: "js",
      code: 'const rejectHandler = (reason) => ({ status: "rejected", reason });\nconst resolveHandler = (value) => ({ status: "fulfilled", value });\n\nPromise.customAllSettled = function (promises) {\n  const convertedPromises = promises.map((p) =>\n    Promise.resolve(p).then(resolveHandler, rejectHandler),\n  );\n\n  return Promise.all(convertedPromises);\n};\n\nPromise.customAllSettled([\n  new Promise((resolve, reject) => setTimeout(() => resolve(1), 1000)),\n  new Promise((resolve, reject) =>\n    setTimeout(() => reject(new Error("Whoops!")), 2000),\n  ),\n  new Promise((resolve, reject) => setTimeout(() => resolve(3), 3000)),\n])\n  .then(console.info)\n  .catch(console.error);',
      createdAt: "2026-07-08T17:47:36.106Z",
      updatedAt: "2026-07-08T17:47:36.106Z",
    },
    {
      id: "a93d31e7-9476-4827-bbd8-86032b796a37",
      slug: "promise-any",
      topicSlug: "promises",
      title: "Implement Promise.any",
      language: "js",
      code: 'Promise.customAny = function (promises) {\n  return new Promise((resolve, reject) => {\n    const errors = [];\n    let remaining = promises.length;\n\n    if (remaining === 0) {\n      return reject(new AggregateError([], "All promises were rejected"));\n    }\n\n    promises.forEach((promise, index) => {\n      Promise.resolve(promise)\n        .then(resolve)\n        .catch((error) => {\n          errors[index] = error;\n          remaining -= 1;\n          if (remaining === 0) {\n            reject(new AggregateError(errors, "All promises were rejected"));\n          }\n        });\n    });\n  });\n};\n\nconst promise1 = Promise.reject(0);\nconst promise2 = new Promise((resolve) => setTimeout(resolve, 100, "quick"));\nconst promise3 = new Promise((resolve) => setTimeout(resolve, 500, "slow"));\n\nconst promises = [promise1, promise2, promise3];\n\nPromise.customAny(promises).then((value) => console.log(value));',
      createdAt: "2026-07-08T17:47:36.136Z",
      updatedAt: "2026-07-08T17:47:36.136Z",
    },
    {
      id: "4e9b8d67-22bc-47d5-aa8c-ff082bfdfe18",
      slug: "promise-race",
      topicSlug: "promises",
      title: "Implement Promise.race",
      language: "js",
      code: 'Promise.customRace = function (promises) {\n  return new Promise((resolve, reject) => {\n    for (const promise of promises) {\n      Promise.resolve(promise).then(resolve, reject);\n    }\n  });\n};\n\nPromise.customRace([\n  new Promise((resolve, reject) => setTimeout(() => resolve(1), 1000)),\n  new Promise((resolve, reject) =>\n    setTimeout(() => reject(new Error("Whoops!")), 2000),\n  ),\n  new Promise((resolve, reject) => setTimeout(() => resolve(3), 3000)),\n]).then(console.log);',
      createdAt: "2026-07-08T17:47:36.167Z",
      updatedAt: "2026-07-08T17:47:36.167Z",
    },
    {
      id: "f136f95d-bb51-4ef8-9b47-6f408f905d73",
      slug: "clsx",
      topicSlug: "random",
      title: "Implement clsx",
      language: "js",
      code: 'function clsx(...args) {\n  const classes = [];\n\n  for (const arg of args) {\n    // Skip the current iteration if the argument is falsy\n    if (!arg) continue;\n\n    if (typeof arg === "string") {\n      classes.push(arg);\n    } else if (Array.isArray(arg)) {\n      classes.push(clsx(...arg)); // Recursively process arrays\n    } else if (typeof arg === "object") {\n      for (const key in arg) {\n        if (arg[key]) {\n          classes.push(key); // Push key if value is truthy\n        }\n      }\n    }\n  }\n\n  return classes.join(" "); // Join classes with a space\n}',
      createdAt: "2026-07-08T17:47:36.194Z",
      updatedAt: "2026-07-08T17:47:36.194Z",
    },
    {
      id: "c41fbc7c-323f-482e-812f-1fb0ad7605ee",
      slug: "filtermap",
      topicSlug: "random",
      title: "Implement filterMap",
      language: "js",
      code: 'export const filterMap = (array, filterBoolean, mapCallback) => {\n  return array.reduce((acc, item, idx) => {\n    if (filterBoolean(item)) {\n      acc.push(mapCallback(item, idx));\n    }\n    return acc;\n  }, []);\n};\n\nconst people = [\n  { name: "Alice", age: 25, active: true },\n  { name: "Bob", age: 30, active: false },\n  { name: "Charlie", age: 35, active: true },\n];\n\nconst activeNames = filterMap(\n  people,\n  (person) => person.active,\n  (person) => person.name,\n);\n\nconsole.log(activeNames)',
      createdAt: "2026-07-08T17:47:36.223Z",
      updatedAt: "2026-07-08T17:47:36.223Z",
    },
    {
      id: "77dafae6-589b-455d-b7aa-510d91d7281c",
      slug: "innerjoin",
      topicSlug: "random",
      title: "Implement innerJoin",
      language: "js",
      code: 'function innerJoin(predicate, records, ids) {\n  return records.filter((record) => ids.some((id) => predicate(record, id)));\n}\n\nconst result = innerJoin(\n  (record, id) => record.id === id,\n  [\n    { id: 824, name: "Richie Furay" },\n    { id: 956, name: "Dewey Martin" },\n    { id: 313, name: "Bruce Palmer" },\n    { id: 456, name: "Stephen Stills" },\n    { id: 177, name: "Neil Young" },\n  ],\n  [177, 456, 999],\n);\n\nconsole.log(result);',
      createdAt: "2026-07-08T17:47:36.253Z",
      updatedAt: "2026-07-08T17:47:36.253Z",
    },
    {
      id: "8a1692ca-34ae-4848-8454-9368a851b879",
      slug: "reducer",
      topicSlug: "random",
      title: "Reducer Pattern with Actions",
      language: "js",
      code: 'function tasksReducer(tasks, action) {\n  switch (action.type) {\n    case "added": {\n      return [\n        ...tasks,\n        {\n          id: action.id,\n          text: action.text,\n          done: false,\n        },\n      ];\n    }\n    case "changed": {\n      return tasks.map((t) => {\n        if (t.id === action.id) {\n          const { type, ...actionNoType } = action;\n          return actionNoType;\n        } else {\n          return t;\n        }\n      });\n    }\n    case "deleted": {\n      return tasks.filter((t) => t.id !== action.id);\n    }\n    default: {\n      throw Error("Unknown action: " + action.type);\n    }\n  }\n}\n\nconst initialState = [];\nconst actions = [\n  { type: "added", id: 1, text: "Visit Kafka Museum" },\n  { type: "added", id: 2, text: "Watch a puppet show" },\n  { type: "deleted", id: 1 },\n  { type: "added", id: 3, text: "Lennon Wall pic" },\n  { type: "changed", id: 3, text: "Lennon Wall", done: true },\n];\nconst finalState = actions.reduce(tasksReducer, initialState);\nconsole.log(finalState);',
      createdAt: "2026-07-08T17:47:36.284Z",
      updatedAt: "2026-07-08T17:47:36.284Z",
    },
    {
      id: "b486af0e-3443-4f79-8695-d28393fcd614",
      slug: "topological-sort",
      topicSlug: "random",
      title: "Topological Sort by Dependencies",
      language: "js",
      code: 'const cards = [\n  { id: 1, dependent: [6, 7, 8] },\n  { id: 2, dependent: [6] },\n  { id: 3, dependent: [] },\n  { id: 4, dependent: [6, 7, 8] },\n  { id: 5, dependent: [6, 8] },\n  { id: 6, dependent: [] },\n  { id: 7, dependent: [6] },\n  { id: 8, dependent: [7] },\n  { id: 9, dependent: [1] },\n  { id: 10, dependent: [9] },\n];\n\nconst getOrderedCards = (cards) => {\n  const result = [];\n  const added = new Set();\n\n  while (result.length < cards.length) {\n    let addedInPass = false;\n\n    for (const card of cards) {\n      if (\n        !added.has(card.id) &&\n        card.dependent.every((dep) => added.has(dep))\n      ) {\n        result.push(card.id);\n        added.add(card.id);\n        addedInPass = true;\n      }\n    }\n\n    if (!addedInPass) {\n      throw new Error("Cannot resolve dependency order");\n    }\n  }\n\n  return result;\n};\n\nconsole.log(getOrderedCards(cards));',
      createdAt: "2026-07-08T17:47:36.316Z",
      updatedAt: "2026-07-08T17:47:36.316Z",
    },
  ],
  meta: {
    total: 71,
    page: 1,
    limit: 100,
    totalPages: 1,
  },
};