const savedSnippets = {
  data: [
    {
      id: "f46dbdca-c92c-4656-b592-84a3c12c2577",
      slug: "concat",
      topicSlug: "array-methods",
      title: "Implement Array.prototype.concat",
      language: "js",
      code: "Array.prototype.myConcat = function (...arrays) {\n  const result = [...this];\n\n  for (const array of arrays) {\n    if (Array.isArray(array)) {\n      result.push(...array);\n    } else {\n      result.push(array);\n    }\n  }\n\n  return result;\n};",
      createdAt: "2026-08-02T10:37:13.002Z",
      updatedAt: "2026-08-02T10:37:13.002Z",
    },
    {
      id: "40195765-fcfa-4f7c-b7fe-a068ebc6ed0d",
      slug: "fill",
      topicSlug: "array-methods",
      title: "Implement Array.prototype.fill",
      language: "js",
      code: "Array.prototype.customFill = function (value, start = 0, end = this.length) {\n  if (start < 0) {\n    start = this.length + start;\n  }\n\n  if (end < 0) {\n    end = this.length + end;\n  }\n\n  for (let i = start; i < Math.min(end, this.length); i++) {\n    this[i] = value;\n  }\n\n  return this;\n};",
      createdAt: "2026-08-02T10:37:13.103Z",
      updatedAt: "2026-08-02T10:37:13.103Z",
    },
    {
      id: "959324ac-d040-4709-ae9c-a0b31ba5c573",
      slug: "pop",
      topicSlug: "array-methods",
      title: "Implement Array.prototype.pop",
      language: "js",
      code: "Array.prototype.customPop = function () {\n  const length = this.length;\n\n  if (length === 0) {\n    return undefined;\n  }\n\n  const lastElement = this[length - 1];\n  this.length = length - 1;\n\n  return lastElement;\n};",
      createdAt: "2026-08-02T10:37:13.155Z",
      updatedAt: "2026-08-02T10:37:13.155Z",
    },
    {
      id: "6f5b9dbe-a52e-4587-82e1-2b5f256e81ae",
      slug: "push",
      topicSlug: "array-methods",
      title: "Implement Array.prototype.push",
      language: "js",
      code: "Array.prototype.customPush = function () {\n  for (let i = 0; i < arguments.length; i++) {\n    this[this.length] = arguments[i];\n  }\n\n  return this.length;\n};",
      createdAt: "2026-08-02T10:37:13.202Z",
      updatedAt: "2026-08-02T10:37:13.202Z",
    },
    {
      id: "fa4a6cae-9766-46db-890a-9b5af6cecc7b",
      slug: "reverse",
      topicSlug: "array-methods",
      title: "Implement Array.prototype.reverse",
      language: "js",
      code: "Array.prototype.customReverse = function () {\n  const middle = Math.floor(this.length / 2);\n\n  for (let i = 0; i < middle; i++) {\n    const temp = this[i];\n    this[i] = this[this.length - 1 - i];\n    this[this.length - 1 - i] = temp;\n  }\n\n  return this;\n};",
      createdAt: "2026-08-02T10:37:13.284Z",
      updatedAt: "2026-08-02T10:37:13.284Z",
    },
    {
      id: "8067ee05-de1d-4c31-a631-ab802a56c728",
      slug: "shift",
      topicSlug: "array-methods",
      title: "Implement Array.prototype.shift",
      language: "js",
      code: "Array.prototype.customShift = function () {\n  if (!this.length) return;\n\n  const firstElement = this[0];\n\n  for (let i = 0; i < this.length; i++) {\n    this[i] = this[i + 1];\n  }\n\n  this.length -= 1;\n\n  return firstElement;\n};",
      createdAt: "2026-08-02T10:37:13.326Z",
      updatedAt: "2026-08-02T10:37:13.326Z",
    },
    {
      id: "40ead9f1-dfe1-4e0c-b61f-0833f13e969c",
      slug: "unshift",
      topicSlug: "array-methods",
      title: "Implement Array.prototype.unshift",
      language: "js",
      code: "Array.prototype.customUnshift = function (...elements) {\n  const originalLength = this.length;\n  const totalLength = elements.length + originalLength;\n\n  // Shift existing elements to the right\n  for (let i = originalLength - 1; i >= 0; i--) {\n    this[i + elements.length] = this[i];\n  }\n\n  // Add new elements at the beginning\n  for (let i = 0; i < elements.length; i++) {\n    this[i] = elements[i];\n  }\n\n  return totalLength; // Return the new length\n};",
      createdAt: "2026-08-02T10:37:13.369Z",
      updatedAt: "2026-08-02T10:37:13.369Z",
    },
    {
      id: "617e7570-2a02-4b21-bf92-5e4206a4bda8",
      slug: "splice",
      topicSlug: "array-methods",
      title: "Implement Array.prototype.splice",
      language: "js",
      code: "Array.prototype.customSplice = function (\n  startIndex,\n  deleteCount,\n  ...itemsToAdd\n) {\n  const length = this.length;\n\n  // Handle negative indices\n  startIndex =\n    startIndex < 0\n      ? Math.max(length + startIndex, 0)\n      : Math.min(startIndex, length);\n\n  // If deleteCount is undefined, remove all elements starting from startIndex\n  if (deleteCount === undefined) {\n    deleteCount = length - startIndex;\n  } else {\n    // Normalize deleteCount\n    deleteCount = Math.max(0, Math.min(deleteCount, length - startIndex));\n  }\n\n  // Extract the array to be deleted\n  const splicedItems = this.slice(startIndex, startIndex + deleteCount);\n\n  // Create the resulting this by combining parts and items to add\n  const remainingItems = [\n    ...this.slice(0, startIndex),\n    ...itemsToAdd,\n    ...this.slice(startIndex + deleteCount),\n  ];\n\n  // Update the original array\n  this.length = 0; // Clear the this\n  for (let i = 0; i < remainingItems.length; i++) {\n    this[i] = remainingItems[i];\n  }\n\n  // Return the deleted items\n  return splicedItems;\n};",
      createdAt: "2026-08-02T10:37:13.753Z",
      updatedAt: "2026-08-02T10:37:13.753Z",
    },
    {
      id: "1ad38e68-c239-487b-bc52-c0086ff40533",
      slug: "filter",
      topicSlug: "array-methods",
      title: "Implement Array.prototype.filter",
      language: "js",
      code: "Array.prototype.myFilter = function (callback) {\n  const result = [];\n\n  for (let i = 0; i < this.length; i++) {\n    if (callback(this[i], i, this)) {\n      result.push(this[i]);\n    }\n  }\n\n  return result;\n};",
      createdAt: "2026-08-02T10:37:13.794Z",
      updatedAt: "2026-08-02T10:37:13.794Z",
    },
    {
      id: "c00d9064-e13e-4f73-a026-4173227c1ba0",
      slug: "flat",
      topicSlug: "array-methods",
      title: "Implement Array.prototype.flat",
      language: "js",
      code: "Array.prototype.customFlat = function (depth = 1) {\n  const result = [];\n\n  const flatten = (array, depth) => {\n    for (const item of array) {\n      if (Array.isArray(item) && depth > 0) {\n        flatten(item, depth - 1);\n      } else {\n        result.push(item);\n      }\n    }\n  };\n  flatten(this, depth);\n\n  return result;\n};",
      createdAt: "2026-08-02T10:37:13.834Z",
      updatedAt: "2026-08-02T10:37:13.834Z",
    },
    {
      id: "c48f3faa-d900-42ae-8870-1a86c681669e",
      slug: "flatmap",
      topicSlug: "array-methods",
      title: "Implement Array.prototype.flatMap",
      language: "js",
      code: "Array.prototype.customFlatMap = function (callback, thisArg) {\n  const result = [];\n\n  for (let i = 0; i < this.length; i++) {\n    const mapped = callback.call(thisArg, this[i], i, this);\n\n    if (Array.isArray(mapped)) {\n      result.push(...mapped); // Use spread operator for flattening\n    } else {\n      result.push(mapped);\n    }\n  }\n\n  return result;\n};",
      createdAt: "2026-08-02T10:37:13.875Z",
      updatedAt: "2026-08-02T10:37:13.875Z",
    },
    {
      id: "09f8940b-1065-47f2-a8dc-b3aec6b57b65",
      slug: "join",
      topicSlug: "array-methods",
      title: "Implement Array.prototype.join",
      language: "js",
      code: 'Array.prototype.customJoin = function (separator = ",") {\n  let result = "";\n\n  for (let i = 0; i < this.length; i++) {\n    if (i > 0) {\n      result += separator;\n    }\n\n    result += this[i];\n  }\n\n  return result;\n};',
      createdAt: "2026-08-02T10:37:13.915Z",
      updatedAt: "2026-08-02T10:37:13.915Z",
    },
    {
      id: "9b08d296-82f4-4d4b-b05b-2217178d4fab",
      slug: "map",
      topicSlug: "array-methods",
      title: "Implement Array.prototype.map",
      language: "js",
      code: 'Array.prototype.customMap = function (callbackFn) {\n  if (typeof callbackFn !== "function") {\n    throw new TypeError("Callback must be a function");\n  }\n\n  const arr = [];\n  for (let i = 0; i < this.length; i++) {\n    arr.push(callbackFn(this[i], i, this));\n  }\n\n  return arr;\n};',
      createdAt: "2026-08-02T10:37:13.957Z",
      updatedAt: "2026-08-02T10:37:13.957Z",
    },
    {
      id: "49022f07-f763-43ea-b17f-daabf4b65f44",
      slug: "reduce",
      topicSlug: "array-methods",
      title: "Implement Array.prototype.reduce",
      language: "js",
      code: "Array.prototype.customReduce = function (callback, initialValue) {\n  let accumulator = initialValue !== undefined ? initialValue : this[0];\n\n  const startIndex = initialValue !== undefined ? 0 : 1;\n\n  for (let i = startIndex; i < this.length; i++) {\n    accumulator = callback(accumulator, this[i], i, this);\n  }\n\n  return accumulator;\n};",
      createdAt: "2026-08-02T10:37:13.996Z",
      updatedAt: "2026-08-02T10:37:13.996Z",
    },
    {
      id: "d1404cfc-f015-45c6-9556-57721bbac75f",
      slug: "slice",
      topicSlug: "array-methods",
      title: "Implement Array.prototype.slice",
      language: "js",
      code: "Array.prototype.customSlice = function (start = 0, end) {\n  const length = this.length;\n  let endIndex = end || length;\n\n  if (start < 0) {\n    start = Math.max(length + start, 0);\n  }\n  if (endIndex < 0) {\n    endIndex = Math.max(length + endIndex, 0);\n  }\n\n  const result = [];\n\n  for (let i = start; i < endIndex && i < length; i++) {\n    result.push(this[i]);\n  }\n\n  return result;\n};",
      createdAt: "2026-08-02T10:37:14.040Z",
      updatedAt: "2026-08-02T10:37:14.040Z",
    },
    {
      id: "11c2c414-653f-4b66-bd99-dd2751792409",
      slug: "find",
      topicSlug: "array-methods",
      title: "Implement Array.prototype.find",
      language: "js",
      code: "Array.prototype.customFind = function (callback) {\n  for (let i = 0; i < this.length; i++) {\n    if (callback(this[i])) {\n      return this[i];\n    }\n  }\n};",
      createdAt: "2026-08-02T10:37:14.083Z",
      updatedAt: "2026-08-02T10:37:14.083Z",
    },
    {
      id: "9faaf1e8-1756-4f7e-b238-fb9d160b2e31",
      slug: "findlast",
      topicSlug: "array-methods",
      title: "Implement Array.prototype.findLast",
      language: "js",
      code: "Array.prototype.customFindLast = function (callback) {\n  for (let i = this.length; i >= 0; i--) {\n    if (callback(this[i])) {\n      return this[i];\n    }\n  }\n};",
      createdAt: "2026-08-02T10:37:14.123Z",
      updatedAt: "2026-08-02T10:37:14.123Z",
    },
    {
      id: "039423ef-986f-4758-a89b-c21c3cd73209",
      slug: "at",
      topicSlug: "array-methods",
      title: "Implement Array.prototype.at",
      language: "js",
      code: "Array.prototype.customAt = function (index) {\n  if (index < 0) {\n    index = this.length + index;\n  }\n\n  return this[index];\n};",
      createdAt: "2026-08-02T10:37:14.163Z",
      updatedAt: "2026-08-02T10:37:14.163Z",
    },
    {
      id: "7afdb65a-3578-4751-82a5-d344b3aa73cd",
      slug: "every",
      topicSlug: "array-methods",
      title: "Implement Array.prototype.every",
      language: "js",
      code: "Array.prototype.customEvery = function (callback) {\n  for (let i = 0; i < this.length; i++) {\n    if (!callback(this[i], i)) {\n      return false;\n    }\n  }\n\n  return true;\n};",
      createdAt: "2026-08-02T10:37:14.203Z",
      updatedAt: "2026-08-02T10:37:14.203Z",
    },
    {
      id: "f9b6bfb3-63b3-42e6-bdea-6e79fdddaa16",
      slug: "includes",
      topicSlug: "array-methods",
      title: "Implement Array.prototype.includes",
      language: "js",
      code: 'function sameValueZero(x, y) {\n  return (\n    x === y ||\n    (typeof x === "number" && typeof y === "number" && x !== x && y !== y)\n  );\n}\n\nArray.prototype.customIncludes = function (searchElement, fromIndex = 0) {\n  const length = this.length;\n\n  if (length === 0) {\n    return false;\n  }\n\n  if (fromIndex < 0) {\n    fromIndex = Math.max(length + fromIndex, 0);\n  }\n\n  for (let i = fromIndex; i < length; i++) {\n    if (sameValueZero(this[i], searchElement)) {\n      return true;\n    }\n  }\n\n  return false;\n};',
      createdAt: "2026-08-02T10:37:14.241Z",
      updatedAt: "2026-08-02T10:37:14.241Z",
    },
    {
      id: "826d5348-ed27-449f-9b79-2672ff7bb35c",
      slug: "some",
      topicSlug: "array-methods",
      title: "Implement Array.prototype.some",
      language: "js",
      code: "Array.prototype.customSome = function (callback) {\n  for (let i = 0; i < this.length; i++) {\n    if (callback(this[i], i, this)) {\n      return true;\n    }\n  }\n\n  return false;\n};",
      createdAt: "2026-08-02T10:37:14.281Z",
      updatedAt: "2026-08-02T10:37:14.281Z",
    },
    {
      id: "5f7d047d-6f84-4e2e-836a-d6f3a22e1578",
      slug: "composition",
      topicSlug: "composition-vs-inheritance",
      title: "Function Composition Pipeline",
      language: "js",
      code: "const dateFunc = () => new Date();\nconst textFunc = (date) => date.toDateString();\nconst labelFunc = (text) => `Today ${text}`;\nconst showLabelFunc = (label) => console.log(label);\n\nconst date = dateFunc();\nconst text = textFunc(date);\nconst label = labelFunc(text);\nshowLabelFunc(label);\n\nfunction pipe(...steps) {\n  return function runSteps() {\n    let result;\n    for (let i = 0; i < steps.length; i++) {\n      let step = steps[i];\n      result = step(result);\n    }\n    return result;\n  };\n}\n\nconst showDateLabel = pipe(dateFunc, textFunc, labelFunc, showLabelFunc);\nshowDateLabel();",
      createdAt: "2026-08-02T10:37:14.317Z",
      updatedAt: "2026-08-02T10:37:14.317Z",
    },
    {
      id: "74b2073b-733f-4233-8d67-8c23f16dc2e6",
      slug: "this",
      topicSlug: "core-concepts",
      title: "thisArg in Array Callbacks",
      language: "js",
      code: '"use strict";\n\nArray.prototype.customFilter = function (callback, thisArg) {\n  let result = [];\n\n  for (let i = 0; i < this.length; i++) {\n    if (callback.call(thisArg, this[i], i, this)) {\n      result.push(this[i]);\n    }\n  }\n\n  return result;\n};\n\nArray.prototype.customFilterNoThis = function (callback) {\n  let result = [];\n\n  for (let i = 0; i < this.length; i++) {\n    if (callback(this[i], i, this)) {\n      result.push(this[i]);\n    }\n  }\n\n  return result;\n};\n\nconst army = {\n  minAge: 18,\n  maxAge: 27,\n  canJoin(user) {\n    return user.age >= this.minAge && user.age < this.maxAge;\n  },\n};\n\nconst users = [{ age: 16 }, { age: 20 }, { age: 23 }, { age: 30 }];\n\nconst soldiers2 = users.customFilterNoThis((user) => army.canJoin(user));\nconst soldiers3 = users.customFilter(army.canJoin, army);\n\nconsole.log(soldiers2);\nconsole.log(soldiers3);',
      createdAt: "2026-08-02T10:37:14.356Z",
      updatedAt: "2026-08-02T10:37:14.356Z",
    },
    {
      id: "4fa57a1a-32b9-4216-b001-a657d33df9b6",
      slug: "object-method-this",
      topicSlug: "core-concepts",
      title: "Broken Object Method Receiver",
      language: "js",
      code: 'let user = {\n  name: "John",\n  sayHi() {\n    console.log(user.name);\n  },\n};\n\nconst admin = user;\nuser = null;\n\nadmin.sayHi();',
      createdAt: "2026-08-02T10:37:14.397Z",
      updatedAt: "2026-08-02T10:37:14.397Z",
    },
    {
      id: "2daf5302-509e-487c-976b-987c5d9b5563",
      slug: "object-method-this-fix",
      topicSlug: "core-concepts",
      title: "Object Method Receiver with this",
      language: "js",
      code: 'let user = {\n  name: "John",\n  sayHi() {\n    console.log(this.name);\n  },\n};\n\nconst admin = user;\nuser = null;\n\nadmin.sayHi();',
      createdAt: "2026-08-02T10:37:14.436Z",
      updatedAt: "2026-08-02T10:37:14.436Z",
    },
    {
      id: "8f34e08f-094c-489e-9660-1a64957ed962",
      slug: "object-literal-this",
      topicSlug: "core-concepts",
      title: "Object Literals and this Binding",
      language: "js",
      code: 'function makeUser() {\n  return {\n    name: "John",\n    ref: this,\n  };\n}\n\nconst user = makeUser();\nconsole.log(user.ref?.name); \n\nfunction makeUserWithMethod() {\n  return {\n    name: "John",\n    ref() {\n      return this;\n    },\n  };\n}\n\nconst user2 = makeUserWithMethod();\nconsole.log(user2.ref().name);',
      createdAt: "2026-08-02T10:37:14.477Z",
      updatedAt: "2026-08-02T10:37:14.477Z",
    },
    {
      id: "8f1845df-d718-45b2-a757-731c3bd4ff94",
      slug: "method-chaining",
      topicSlug: "core-concepts",
      title: "Method Chaining with this",
      language: "js",
      code: "const ladder = {\n  step: 0,\n  up() {\n    this.step++;\n    return this;\n  },\n  down() {\n    this.step--;\n    return this;\n  },\n  showStep() {\n    console.log(this.step);\n    return this;\n  },\n};\n\nladder.up().up().down().showStep().down().showStep();",
      createdAt: "2026-08-02T10:37:14.517Z",
      updatedAt: "2026-08-02T10:37:14.517Z",
    },
    {
      id: "04679461-6366-4b8b-835e-39cb4c56077c",
      slug: "for-vs-while",
      topicSlug: "core-concepts",
      title: "Pre-Increment vs Post-Increment in Loops",
      language: "js",
      code: "let i = 0;\nwhile (++i < 3) console.log(i);\n\nlet i2 = 0;\nwhile (i2++ < 3) console.log(i2);\n\nfor (let i = 0; i < 3; i++) console.log(i);\n\nfor (let i = 0; i < 3; ++i) console.log(i);",
      createdAt: "2026-08-02T10:37:14.557Z",
      updatedAt: "2026-08-02T10:37:14.557Z",
    },
    {
      id: "e6e8ab43-192a-4886-b901-a3fb4602193a",
      slug: "bind",
      topicSlug: "core-concepts",
      title: "Lost Method Receiver in setTimeout",
      language: "js",
      code: 'const user = {\n  firstName: "John",\n  sayHi() {\n    console.log(`Hello, ${this.firstName}!`);\n  },\n};\n\nuser.sayHi();\nsetTimeout(user.sayHi, 0);',
      createdAt: "2026-08-02T10:37:14.598Z",
      updatedAt: "2026-08-02T10:37:14.598Z",
    },
    {
      id: "f346ae67-d125-46d8-a12b-4edde9eea0eb",
      slug: "call-and-arrows",
      topicSlug: "core-concepts",
      title: "call with Regular and Arrow Functions",
      language: "js",
      code: "const obj = {\n  value: 25,\n  regularMethod() {\n    return this.value;\n  },\n  arrowMethod: () => {\n    return this?.value;\n  },\n};\n\nconst anotherObj = {\n  value: 50,\n};",
      createdAt: "2026-08-02T10:37:14.638Z",
      updatedAt: "2026-08-02T10:37:14.638Z",
    },
    {
      id: "56943aee-6491-4d23-9926-fd070cd90099",
      slug: "object-create",
      topicSlug: "core-concepts",
      title: "Prototype Inheritance with Object.create",
      language: "js",
      code: 'const vehicle = {\n  getInfo() {\n    console.log(`${this.model} was made in ${this.year}`);\n  },\n};\n\nconst myCar = Object.create(vehicle);\nmyCar.model = "BMW";\nmyCar.year = 2010;\n\nmyCar.getInfo();',
      createdAt: "2026-08-02T10:37:14.678Z",
      updatedAt: "2026-08-02T10:37:14.678Z",
    },
    {
      id: "67730977-66c9-4db6-9b9e-4b2e9704db89",
      slug: "async-generator",
      topicSlug: "core-concepts",
      title: "Async Generator Sequence",
      language: "js",
      code: "async function* generateSequence(start, end) {\n  for (let i = start; i <= end; i++) {\n    await new Promise((resolve) => setTimeout(resolve, 1000));\n    yield i;\n  }\n}\n\nconst timer = async (callback) => {\n  const generator = generateSequence(1, 5);\n  for await (let value of generator) {\n    callback(value);\n  }\n};",
      createdAt: "2026-08-02T10:37:14.720Z",
      updatedAt: "2026-08-02T10:37:14.720Z",
    },
    {
      id: "0447fe6f-6d80-4a21-bc2e-da2c76d06c4f",
      slug: "function-stack",
      topicSlug: "core-concepts",
      title: "Recursive Call Stack Order",
      language: "js",
      code: "function foo(i) {\n  if (i < 0) {\n    return;\n  }\n  console.log(`begin: ${i}`);\n  foo(i - 1);\n  console.log(`end: ${i}`);\n}",
      createdAt: "2026-08-02T10:37:15.069Z",
      updatedAt: "2026-08-02T10:37:15.069Z",
    },
    {
      id: "51cd825a-5e64-4f4a-9651-61e1e1bf5e8f",
      slug: "lexical-environment-scope-fixed",
      topicSlug: "core-concepts",
      title: "Closure Capture in Loops",
      language: "js",
      code: "function makeArmy() {\n  const shooters = [];\n\n  let i = 0;\n  while (i < 10) {\n    let j = i;\n    const shooter = function () {\n      return j;\n    };\n    shooters.push(shooter);\n    i++;\n  }\n\n  return shooters;\n}\n\nconst army = makeArmy();\n\nconsole.log(army[0]());\nconsole.log(army[1]());\nconsole.log(army[5]());",
      createdAt: "2026-08-02T10:37:15.109Z",
      updatedAt: "2026-08-02T10:37:15.109Z",
    },
    {
      id: "15a0f4e8-a7b0-45b6-ad70-20096a5873f4",
      slug: "lexical-environment-scope-broken",
      topicSlug: "core-concepts",
      title: "Broken Closure Scope in Loops",
      language: "js",
      code: "function makeArmy() {\n  const shooters = [];\n\n  let i = 0;\n  while (i < 10) {\n    const shooter = function () {\n      return i;\n    };\n    shooters.push(shooter);\n    i++;\n  }\n\n  return shooters;\n}\n\nconst army = makeArmy();\n\nconsole.log(army[0]());\nconsole.log(army[1]());\nconsole.log(army[5]());",
      createdAt: "2026-08-02T10:37:15.150Z",
      updatedAt: "2026-08-02T10:37:15.150Z",
    },
    {
      id: "e0195d38-cfbb-42ae-918d-59edb452710d",
      slug: "output-every-second",
      topicSlug: "debounce-throttle",
      title: "Interval-Based Number Printer",
      language: "js",
      code: "function printNumbers(from, to) {\n  let current = from;\n  let timerId;\n\n  function go() {\n    console.log(current);\n    if (current === to) {\n      clearInterval(timerId);\n    }\n    current++;\n  }\n\n  go();\n  timerId = setInterval(go, 1000);\n}\n\nprintNumbers(5, 10);",
      createdAt: "2026-08-02T10:37:15.190Z",
      updatedAt: "2026-08-02T10:37:15.190Z",
    },
    {
      id: "33a0c957-550f-4571-835c-a9cde077ff9c",
      slug: "output-every-second-2",
      topicSlug: "debounce-throttle",
      title: "Timeout-Based Number Printer",
      language: "js",
      code: "function printNumbers(from, to) {\n  let current = from;\n\n  function go() {\n    console.log(current);\n    if (current < to) {\n      setTimeout(go, 1000);\n    }\n    current++;\n  }\n\n  go();\n}\n\nprintNumbers(5, 10);",
      createdAt: "2026-08-02T10:37:15.231Z",
      updatedAt: "2026-08-02T10:37:15.231Z",
    },
    {
      id: "124280c1-3de2-409f-a9f3-bd5aba228e81",
      slug: "debounce",
      topicSlug: "debounce-throttle",
      title: "Implement debounce",
      language: "js",
      code: 'function debounce(func, ms) {\n  let timeout;\n\n  return function (...args) {\n    clearTimeout(timeout);\n    timeout = setTimeout(() => func.apply(this, args), ms);\n  };\n}\n\nconst timeLoggedConsoleLog = (...args) => {\n  console.log(`Logged after ${Date.now() - startTime} ms:`, ...args);\n};\n\nconst startTime = Date.now();\nconst f = debounce(timeLoggedConsoleLog, 500);\n\nf("a");\nsetTimeout(() => f("b"), 200);\nsetTimeout(() => f("c"), 600);\nsetTimeout(() => f("d"), 600);\nsetTimeout(() => f("e"), 600); // Logged after 1118 ms: e',
      createdAt: "2026-08-02T10:37:15.270Z",
      updatedAt: "2026-08-02T10:37:15.270Z",
    },
    {
      id: "5e342eee-cd7d-472b-a793-ed664a5e27f2",
      slug: "throttle",
      topicSlug: "debounce-throttle",
      title: "Implement throttle",
      language: "js",
      code: "function throttle(fn, limit) {\n  let inThrottle;\n\n  return function (...args) {\n    if (inThrottle) return;\n    fn.apply(this, args);\n    inThrottle = true;\n    setTimeout(() => (inThrottle = false), limit);\n  };\n}\n\nconst timeLoggedConsoleLog = (...args) => {\n  console.log(`Logged after ${Date.now() - startTime} ms:`, ...args);\n};\n\nconst startTime = Date.now();\nconst f = throttle(timeLoggedConsoleLog, 500);",
      createdAt: "2026-08-02T10:37:15.309Z",
      updatedAt: "2026-08-02T10:37:15.309Z",
    },
    {
      id: "ad8bf6f9-4a42-4195-b207-a983a020528f",
      slug: "promise-all-and-the-event-loop",
      topicSlug: "event-loop",
      title: "Promise.all and Event Loop Timing",
      language: "js",
      code: 'const promise1 = Promise.resolve(3);\nconst promise2 = new Promise((resolve, reject) => {\n  setTimeout(resolve, 1000, "foo");\n});\nconst promise3 = 42;\n\nPromise.all([promise1, promise2, promise3]).then((values) => {\n  console.log({ values });\n});\n\n// Using setTimeout, we can execute code after the queue is empty\nsetTimeout(() => {\n  console.log("the queue is now empty");\n});\n\nconst p3 = Promise.all([]); // Will be immediately resolved\nconst p4 = Promise.all([1337, "hi"]);\n\n// Non-promise values are ignored, but the evaluation is done asynchronously\nconsole.log({ p3 });\nconsole.log({ p4 });\n\nsetTimeout(() => {\n  console.log({ p4 });\n});\n\nPromise.all([promise1, promise2, promise3]).then((values) => {\n  console.log({ values2: values });\n});\n\nconst promise4 = Promise.resolve(3);\nconst promise5 = 42;\n\nPromise.all([promise4, promise5]).then((values) => {\n  console.log({ values3: values });\n});',
      createdAt: "2026-08-02T10:37:15.382Z",
      updatedAt: "2026-08-02T10:37:15.382Z",
    },
    {
      id: "af146dbd-f9c6-4eb2-9528-1c72d4ffd699",
      slug: "promise-chaining-and-microtask-queue-order",
      topicSlug: "event-loop",
      title: "Promise Chain Microtask Order",
      language: "js",
      code: "const promise1 = Promise.resolve();\nconst promise2 = Promise.resolve();\n\npromise1.then(() => console.log(1)).then(() => console.log(2));\npromise2.then(() => console.log(3)).then(() => console.log(4));",
      createdAt: "2026-08-02T10:37:15.422Z",
      updatedAt: "2026-08-02T10:37:15.422Z",
    },
    {
      id: "b5d20682-e701-4bfa-9d3d-2ecd516c9e40",
      slug: "let-in-loops-with-settimeout",
      topicSlug: "event-loop",
      title: "let in Loops with setTimeout",
      language: "js",
      code: "for (let i = 0; i < 4; i++) {\n  setTimeout(() => {\n    console.log(i);\n  }, 1000);\n}",
      createdAt: "2026-08-02T10:37:15.461Z",
      updatedAt: "2026-08-02T10:37:15.461Z",
    },
    {
      id: "2ca35ccf-1c37-42ae-80b8-553dff0992b1",
      slug: "promise-lifecycle-and-event-loop-timing",
      topicSlug: "event-loop",
      title: "Promise Lifecycle Timing",
      language: "js",
      code: 'const promise = new Promise((resolve, reject) => {\n  console.log("Promise callback");\n  resolve("resolved");\n  console.log("Promise callback end");\n}).then((result) => {\n  console.log("Promise callback (.then)", result);\n});\n\nsetTimeout(() => {\n  console.log("event-loop cycle: Promise (fulfilled)", promise);\n}, 0);\n\nconsole.log("Promise (pending)", promise);',
      createdAt: "2026-08-02T10:37:15.505Z",
      updatedAt: "2026-08-02T10:37:15.505Z",
    },
    {
      id: "ea112494-9444-479f-ad1c-cc61574daa95",
      slug: "async-function-and-timer-execution-order",
      topicSlug: "event-loop",
      title: "Async Function and Timer Ordering",
      language: "js",
      code: 'async function run() {\n  console.log("run async");\n  setTimeout(() => {\n    console.log("run timeout");\n  }, 0);\n}\n\nsetTimeout(() => {\n  console.log("timeout");\n}, 0);\n\n// await or not, same result\nawait run();\n\nconsole.log("script");',
      createdAt: "2026-08-02T10:37:15.546Z",
      updatedAt: "2026-08-02T10:37:15.546Z",
    },
    {
      id: "db54f127-5da3-4f31-b5e6-c17596debfd4",
      slug: "blocking-the-event-loop-with-a-while-loop",
      topicSlug: "event-loop",
      title: "Blocking the Event Loop with a While Loop",
      language: "js",
      code: 'const seconds = new Date().getTime() / 1000;\n\nsetTimeout(() => {\n  // prints out "2", meaning that the callback is not called immediately after 500 milliseconds.\n  console.log(`Ran after ${new Date().getTime() / 1000 - seconds} seconds`);\n}, 500);\n\nwhile (true) {\n  if (new Date().getTime() / 1000 - seconds >= 2) {\n    console.log("Good, looped for 2 seconds");\n    break;\n  }\n}',
      createdAt: "2026-08-02T10:37:15.586Z",
      updatedAt: "2026-08-02T10:37:15.586Z",
    },
    {
      id: "f21d3ba8-1abe-4a48-a606-b878294259fd",
      slug: "script-microtasks-and-macrotasks-in-execution-order",
      topicSlug: "event-loop",
      title: "Script, Microtask, and Macrotask Order",
      language: "js",
      code: 'console.log("Script start");\n\nsetTimeout(() => {\n  console.log("setTimeout");\n}, 0);\n\nPromise.resolve()\n  .then(() => {\n    console.log("Promise 1");\n  })\n  .then(() => {\n    console.log("Promise 2");\n  });\n\nconsole.log("Script end");\n\nconst promise1 = new Promise((resolve, reject) => {\n  console.log("Promise constructor");\n  resolve();\n}).then(() => {\n  console.log("Promise constructor resolve");\n});\n\nqueueMicrotask(() => {\n  console.log("Microtask queue");\n});\n\nconsole.log("After Promise constructor");',
      createdAt: "2026-08-02T10:37:15.627Z",
      updatedAt: "2026-08-02T10:37:15.627Z",
    },
    {
      id: "8584c05a-c775-4600-be05-0b86ff02dda3",
      slug: "blocking-inside-async-callbacks",
      topicSlug: "event-loop",
      title: "Blocking Work Inside Async Callbacks",
      language: "js",
      code: 'function longRunningTask() {\n  console.log("Start Long-Running Task");\n\n  const startTime = Date.now();\n  while (Date.now() - startTime < 2000) {\n    // Simulate a long-running task (2 seconds)\n  }\n\n  console.log("Long-Running Task Completed");\n}\n\nfunction simulateNonBlocking() {\n  console.log("Start");\n\n  setTimeout(() => {\n    console.log("Non-blocking Operation");\n    longRunningTask();\n  }, 0);\n\n  console.log("End");\n}\n\nsimulateNonBlocking();',
      createdAt: "2026-08-02T10:37:15.668Z",
      updatedAt: "2026-08-02T10:37:15.668Z",
    },
    {
      id: "41a26803-e00e-4bb4-9390-c1e3ad69a93c",
      slug: "nested-microtasks-in-macrotasks",
      topicSlug: "event-loop",
      title: "Nested Microtasks Inside Macrotasks",
      language: "js",
      code: 'console.log("Start");\n\nsetTimeout(() => {\n  console.log("setTimeout 1");\n  Promise.resolve().then(() => {\n    console.log("Promise inside setTimeout 1");\n  });\n}, 0);\n\nsetTimeout(() => {\n  console.log("setTimeout 2");\n}, 0);\n\nPromise.resolve()\n  .then(() => {\n    console.log("Promise 1");\n  })\n  .then(() => {\n    console.log("Promise 2");\n  });\n\nconsole.log("End");',
      createdAt: "2026-08-02T10:37:15.706Z",
      updatedAt: "2026-08-02T10:37:15.706Z",
    },
    {
      id: "e60096c5-2c45-4f0c-98af-6bbb28a27643",
      slug: "requestanimationframe-and-task-ordering",
      topicSlug: "event-loop",
      title: "requestAnimationFrame and Task Ordering",
      language: "js",
      code: 'console.log("1");\n\nsetTimeout(function () {\n  console.log("2");\n\n  Promise.resolve().then(function () {\n    console.log("3");\n  });\n}, 0);\n\nPromise.resolve().then(function () {\n  console.log("4");\n\n  setTimeout(function () {\n    console.log("5");\n  }, 0);\n});\n\nrequestAnimationFrame(function () {\n  console.log("7");\n});\n\nconsole.log("6");',
      createdAt: "2026-08-02T10:37:15.745Z",
      updatedAt: "2026-08-02T10:37:15.745Z",
    },
    {
      id: "331c86e4-b2e9-40b4-ba7f-4940f57a01a7",
      slug: "has-path-dfs",
      topicSlug: "graph-traversal",
      title: "Directed Graph Path Search with DFS",
      language: "ts",
      code: "type Graph = Record<string, string[]>;\n\n// Depth-First Search\nconst hasPath = (graph: Graph, src: string, dst: string): boolean => {\n  if (src === dst) return true;\n\n  for (const neighbor of graph[src]) {\n    if (hasPath(graph, neighbor, dst)) {\n      return true;\n    }\n  }\n\n  return false;\n};",
      createdAt: "2026-08-02T10:37:15.784Z",
      updatedAt: "2026-08-02T10:37:15.784Z",
    },
    {
      id: "e49dd80c-f770-4bda-b885-2c53eee86c8c",
      slug: "has-path-bfs",
      topicSlug: "graph-traversal",
      title: "Directed Graph Path Search with BFS",
      language: "ts",
      code: "type Graph = Record<string, string[]>;\n\nconst hasPath = (\n  graph: Graph,\n  src: string,\n  dst: string,\n): boolean => {\n  const queue: string[] = [src];\n\n  while (queue.length) {\n    const current = queue.shift();\n    if (current === dst) return true;\n\n    if (current && graph[current]) {\n      for (const neighbor of graph[current]) {\n        queue.push(neighbor);\n      }\n    }\n  }\n\n  return false;\n};",
      createdAt: "2026-08-02T10:37:15.822Z",
      updatedAt: "2026-08-02T10:37:15.822Z",
    },
    {
      id: "006efd1c-a3dc-4554-a646-32baff6cb535",
      slug: "undirected-path",
      topicSlug: "graph-traversal",
      title: "Undirected Graph Path Search",
      language: "ts",
      code: "const undirectedPath = (\n  edges: [string, string][],\n  nodeA: string,\n  nodeB: string,\n): boolean => {\n  const graph = buildGraph(edges);\n  return hasPath(graph, nodeA, nodeB, new Set());\n};\n\nconst buildGraph = (edges: [string, string][]) => {\n  const graph: Record<string, string[]> = {};\n\n  for (const [a, b] of edges) {\n    if (!(a in graph)) graph[a] = [];\n    if (!(b in graph)) graph[b] = [];\n    graph[a].push(b);\n    graph[b].push(a);\n  }\n\n  return graph;\n};\n\nconst hasPath = (\n  graph: Record<string, string[]>,\n  src: string,\n  dst: string,\n  visited: Set<string>,\n): boolean => {\n  if (src === dst) return true;\n  if (visited.has(src)) return false;\n  visited.add(src);\n\n  for (const neighbor of graph[src]) {\n    if (hasPath(graph, neighbor, dst, visited)) {\n      return true;\n    }\n  }\n\n  return false;\n};",
      createdAt: "2026-08-02T10:37:15.862Z",
      updatedAt: "2026-08-02T10:37:15.862Z",
    },
    {
      id: "a896f38b-9a39-430d-ace7-b2c63d4c828e",
      slug: "keyby",
      topicSlug: "lodash",
      title: "Implement keyBy",
      language: "js",
      code: 'function keyBy(collection, iteratee) {\n  const result = {};\n\n  for (const item of collection) {\n    const key =\n      typeof iteratee === "function" ? iteratee(item) : item[iteratee];\n    result[key] = item;\n  }\n\n  return result;\n}',
      createdAt: "2026-08-02T10:37:15.904Z",
      updatedAt: "2026-08-02T10:37:15.904Z",
    },
    {
      id: "1a5716d0-e0d7-4876-8d86-1ef202138984",
      slug: "omit",
      topicSlug: "lodash",
      title: "Implement omit",
      language: "js",
      code: "function omit(obj, keys) {\n  const result = { ...obj };\n\n  if (!Array.isArray(keys)) {\n    delete result[keys];\n    return result;\n  }\n\n  for (const key of keys) {\n    delete result[key];\n  }\n\n  return result;\n}",
      createdAt: "2026-08-02T10:37:15.941Z",
      updatedAt: "2026-08-02T10:37:15.941Z",
    },
    {
      id: "c81d66c8-6b8a-432f-bede-c559e7c112c3",
      slug: "orderby",
      topicSlug: "lodash",
      title: "Implement orderBy",
      language: "js",
      code: 'function orderBy(array, property, order = "asc") {\n  const multiplier = order === "asc" ? 1 : -1;\n  const copy = [...array];\n\n  return copy.sort((a, b) => {\n    if (a[property] < b[property]) return -1 * multiplier;\n    if (a[property] > b[property]) return 1 * multiplier;\n    return 0;\n  });\n}',
      createdAt: "2026-08-02T10:37:15.981Z",
      updatedAt: "2026-08-02T10:37:15.981Z",
    },
    {
      id: "5e67d852-8af8-41b2-890f-544207e45a20",
      slug: "pick",
      topicSlug: "lodash",
      title: "Implement pick",
      language: "js",
      code: 'function pick(obj, keys) {\n  if (typeof keys === "string") {\n    return obj[keys] !== undefined ? { [keys]: obj[keys] } : {};\n  }\n\n  return (Array.isArray(keys) ? keys : []).reduce((result, key) => {\n    if (key in obj) {\n      result[key] = obj[key];\n    }\n    return result;\n  }, {});\n}',
      createdAt: "2026-08-02T10:37:16.024Z",
      updatedAt: "2026-08-02T10:37:16.024Z",
    },
    {
      id: "2ed62b52-2ef6-4654-96ee-840f2fec96ab",
      slug: "curry",
      topicSlug: "lodash",
      title: "Implement curry",
      language: "js",
      code: "function curry(fn) {\n  return function curried(...args) {\n    if (args.length >= fn.length) {\n      return fn(...args);\n    } else {\n      return (...nextArgs) => curried(...args, ...nextArgs);\n    }\n  };\n}",
      createdAt: "2026-08-02T10:37:16.066Z",
      updatedAt: "2026-08-02T10:37:16.066Z",
    },
    {
      id: "c3bfa773-3645-46e1-be24-1bb1e17860d2",
      slug: "difference",
      topicSlug: "lodash",
      title: "Implement difference",
      language: "js",
      code: "const findDifference = function (arr1, arr2) {\n  const set1 = new Set(arr1);\n  const set2 = new Set(arr2);\n\n  const diffLeft = [];\n  const diffRight = [];\n\n  for (const item of set1) {\n    if (!set2.has(item)) diffLeft.push(item);\n  }\n\n  for (const item of set2) {\n    if (!set1.has(item)) diffRight.push(item);\n  }\n\n  return [diffLeft, diffRight];\n};",
      createdAt: "2026-08-02T10:37:16.230Z",
      updatedAt: "2026-08-02T10:37:16.230Z",
    },
    {
      id: "50e72a9d-3414-4fe6-94fe-34713fd45d3d",
      slug: "differenceby",
      topicSlug: "lodash",
      title: "Implement differenceBy",
      language: "js",
      code: "const differenceBy = (arr1, arr2, key) => {\n  const set2 = new Set(arr2.map((item) => item[key]));\n  const set1 = new Set(arr1.map((item) => item[key]));\n\n  const diffLeft = [];\n  const diffRight = [];\n\n  for (const item of arr1) {\n    if (!set2.has(item[key])) {\n      diffLeft.push(item);\n    }\n  }\n\n  for (const item of arr2) {\n    if (!set1.has(item[key])) {\n      diffRight.push(item);\n    }\n  }\n\n  return [diffLeft, diffRight];\n};",
      createdAt: "2026-08-02T10:37:16.353Z",
      updatedAt: "2026-08-02T10:37:16.353Z",
    },
    {
      id: "1a0c9b61-0e02-41e0-8057-91847de0c8f1",
      slug: "intersection",
      topicSlug: "lodash",
      title: "Implement intersection",
      language: "js",
      code: "const intersection = function (nums1, nums2) {\n  const set1 = new Set(nums1);\n  const set2 = new Set(nums2);\n  const result = [];\n\n  for (const nums of set2) {\n    if (set1.has(nums)) {\n      result.push(nums);\n    }\n  }\n\n  return result;\n};",
      createdAt: "2026-08-02T10:37:16.394Z",
      updatedAt: "2026-08-02T10:37:16.394Z",
    },
    {
      id: "d0c3e0e2-cf30-43f6-8ef2-7d078c243df6",
      slug: "union",
      topicSlug: "lodash",
      title: "Implement union",
      language: "js",
      code: "const union = (...arrays) => {\n  return Array.from(new Set([].concat(...arrays)));\n};",
      createdAt: "2026-08-02T10:37:16.440Z",
      updatedAt: "2026-08-02T10:37:16.440Z",
    },
    {
      id: "310e2cad-bf53-4f89-9992-5550c70ba6d6",
      slug: "object-groupby",
      topicSlug: "map-and-set",
      title: "Implement Object.groupBy",
      language: "js",
      code: "const groupBy = (arr, callback) => {\n  return arr.reduce((acc = {}, item) => {\n    const key = callback(item);\n    if (!acc[key]) acc[key] = [];\n    acc[key].push(item);\n\n    return acc;\n  }, {});\n};",
      createdAt: "2026-08-02T10:37:16.480Z",
      updatedAt: "2026-08-02T10:37:16.480Z",
    },
    {
      id: "2c252793-1a64-4b68-b89c-61cf795407f4",
      slug: "promise-all",
      topicSlug: "promises",
      title: "Implement Promise.all",
      language: "js",
      code: 'function myPromiseAll(promises) {\n  return new Promise((resolve, reject) => {\n    if (!Array.isArray(promises)) {\n      return reject(new TypeError("Argument must be an array"));\n    }\n\n    const results = [];\n    let completedPromises = 0;\n\n    for (let index = 0; index < promises.length; index++) {\n      Promise.resolve(promises[index])\n        .then((value) => {\n          results[index] = value;\n          console.log(value);\n          completedPromises += 1;\n          if (completedPromises === promises.length) {\n            resolve(results);\n          }\n        })\n        .catch(reject);\n    }\n\n    if (promises.length === 0) {\n      resolve([]);\n    }\n  });\n}\n\nconst promise1 = new Promise((resolve, reject) => {\n  setTimeout(resolve, 3000, "first");\n});\nconst promise2 = new Promise((resolve, reject) => {\n  setTimeout(resolve, 1000, "second");\n});\nconst promise3 = new Promise((resolve, reject) => {\n  setTimeout(resolve, 5000, "third");\n});\n\nmyPromiseAll([promise1, promise2, promise3]).then((values) => {\n  console.log(values);\n});',
      createdAt: "2026-08-02T10:37:16.521Z",
      updatedAt: "2026-08-02T10:37:16.521Z",
    },
    {
      id: "bcf098a6-2eea-4484-9382-3e4a429ead0b",
      slug: "promise-allsettled",
      topicSlug: "promises",
      title: "Implement Promise.allSettled",
      language: "js",
      code: 'const rejectHandler = (reason) => ({ status: "rejected", reason });\nconst resolveHandler = (value) => ({ status: "fulfilled", value });\n\nPromise.customAllSettled = function (promises) {\n  const convertedPromises = promises.map((p) =>\n    Promise.resolve(p).then(resolveHandler, rejectHandler),\n  );\n\n  return Promise.all(convertedPromises);\n};\n\nPromise.customAllSettled([\n  new Promise((resolve, reject) => setTimeout(() => resolve(1), 1000)),\n  new Promise((resolve, reject) =>\n    setTimeout(() => reject(new Error("Whoops!")), 2000),\n  ),\n  new Promise((resolve, reject) => setTimeout(() => resolve(3), 3000)),\n])\n  .then(console.info)\n  .catch(console.error);',
      createdAt: "2026-08-02T10:37:16.559Z",
      updatedAt: "2026-08-02T10:37:16.559Z",
    },
    {
      id: "e4be3b91-5fec-463d-8baf-4dc7e50b8b84",
      slug: "promise-any",
      topicSlug: "promises",
      title: "Implement Promise.any",
      language: "js",
      code: 'Promise.customAny = function (promises) {\n  return new Promise((resolve, reject) => {\n    const errors = [];\n    let remaining = promises.length;\n\n    if (remaining === 0) {\n      return reject(new AggregateError([], "All promises were rejected"));\n    }\n\n    promises.forEach((promise, index) => {\n      Promise.resolve(promise)\n        .then(resolve)\n        .catch((error) => {\n          errors[index] = error;\n          remaining -= 1;\n          if (remaining === 0) {\n            reject(new AggregateError(errors, "All promises were rejected"));\n          }\n        });\n    });\n  });\n};\n\nconst promise1 = Promise.reject(0);\nconst promise2 = new Promise((resolve) => setTimeout(resolve, 100, "quick"));\nconst promise3 = new Promise((resolve) => setTimeout(resolve, 500, "slow"));\n\nconst promises = [promise1, promise2, promise3];\n\nPromise.customAny(promises).then((value) => console.log(value));',
      createdAt: "2026-08-02T10:37:16.597Z",
      updatedAt: "2026-08-02T10:37:16.597Z",
    },
    {
      id: "70283484-dd2e-4fa1-93fa-f22686b583e4",
      slug: "promise-race",
      topicSlug: "promises",
      title: "Implement Promise.race",
      language: "js",
      code: 'Promise.customRace = function (promises) {\n  return new Promise((resolve, reject) => {\n    for (const promise of promises) {\n      Promise.resolve(promise).then(resolve, reject);\n    }\n  });\n};\n\nPromise.customRace([\n  new Promise((resolve, reject) => setTimeout(() => resolve(1), 1000)),\n  new Promise((resolve, reject) =>\n    setTimeout(() => reject(new Error("Whoops!")), 2000),\n  ),\n  new Promise((resolve, reject) => setTimeout(() => resolve(3), 3000)),\n]).then(console.log);',
      createdAt: "2026-08-02T10:37:16.636Z",
      updatedAt: "2026-08-02T10:37:16.636Z",
    },
    {
      id: "a8d2e80e-afb8-4b21-82a7-3b1a93150908",
      slug: "clsx",
      topicSlug: "random",
      title: "Implement clsx",
      language: "js",
      code: 'function clsx(...args) {\n  const classes = [];\n\n  for (const arg of args) {\n    // Skip the current iteration if the argument is falsy\n    if (!arg) continue;\n\n    if (typeof arg === "string") {\n      classes.push(arg);\n    } else if (Array.isArray(arg)) {\n      classes.push(clsx(...arg)); // Recursively process arrays\n    } else if (typeof arg === "object") {\n      for (const key in arg) {\n        if (arg[key]) {\n          classes.push(key); // Push key if value is truthy\n        }\n      }\n    }\n  }\n\n  return classes.join(" "); // Join classes with a space\n}',
      createdAt: "2026-08-02T10:37:16.679Z",
      updatedAt: "2026-08-02T10:37:16.679Z",
    },
    {
      id: "2d37c8a9-54f0-4480-8cdf-ffdafdc45873",
      slug: "filtermap",
      topicSlug: "random",
      title: "Implement filterMap",
      language: "js",
      code: 'export const filterMap = (array, filterBoolean, mapCallback) => {\n  return array.reduce((acc, item, idx) => {\n    if (filterBoolean(item)) {\n      acc.push(mapCallback(item, idx));\n    }\n    return acc;\n  }, []);\n};\n\nconst people = [\n  { name: "Alice", age: 25, active: true },\n  { name: "Bob", age: 30, active: false },\n  { name: "Charlie", age: 35, active: true },\n];\n\nconst activeNames = filterMap(\n  people,\n  (person) => person.active,\n  (person) => person.name,\n);\n\nconsole.log(activeNames)',
      createdAt: "2026-08-02T10:37:16.719Z",
      updatedAt: "2026-08-02T10:37:16.719Z",
    },
    {
      id: "42d9e89e-76d7-4f69-83f8-c373047dc1ba",
      slug: "innerjoin",
      topicSlug: "random",
      title: "Implement innerJoin",
      language: "js",
      code: 'function innerJoin(predicate, records, ids) {\n  return records.filter((record) => ids.some((id) => predicate(record, id)));\n}\n\nconst result = innerJoin(\n  (record, id) => record.id === id,\n  [\n    { id: 824, name: "Richie Furay" },\n    { id: 956, name: "Dewey Martin" },\n    { id: 313, name: "Bruce Palmer" },\n    { id: 456, name: "Stephen Stills" },\n    { id: 177, name: "Neil Young" },\n  ],\n  [177, 456, 999],\n);\n\nconsole.log(result);',
      createdAt: "2026-08-02T10:37:16.757Z",
      updatedAt: "2026-08-02T10:37:16.757Z",
    },
    {
      id: "92a51970-4e03-49ee-a90d-04286229b816",
      slug: "reducer",
      topicSlug: "random",
      title: "Reducer Pattern with Actions",
      language: "js",
      code: 'function tasksReducer(tasks, action) {\n  switch (action.type) {\n    case "added": {\n      return [\n        ...tasks,\n        {\n          id: action.id,\n          text: action.text,\n          done: false,\n        },\n      ];\n    }\n    case "changed": {\n      return tasks.map((t) => {\n        if (t.id === action.id) {\n          const { type, ...actionNoType } = action;\n          return actionNoType;\n        } else {\n          return t;\n        }\n      });\n    }\n    case "deleted": {\n      return tasks.filter((t) => t.id !== action.id);\n    }\n    default: {\n      throw Error("Unknown action: " + action.type);\n    }\n  }\n}\n\nconst initialState = [];\nconst actions = [\n  { type: "added", id: 1, text: "Visit Kafka Museum" },\n  { type: "added", id: 2, text: "Watch a puppet show" },\n  { type: "deleted", id: 1 },\n  { type: "added", id: 3, text: "Lennon Wall pic" },\n  { type: "changed", id: 3, text: "Lennon Wall", done: true },\n];\nconst finalState = actions.reduce(tasksReducer, initialState);\nconsole.log(finalState);',
      createdAt: "2026-08-02T10:37:16.795Z",
      updatedAt: "2026-08-02T10:37:16.795Z",
    },
    {
      id: "1222b3ee-267e-4dcf-94e5-4f2d1c97ba40",
      slug: "topological-sort",
      topicSlug: "random",
      title: "Topological Sort by Dependencies",
      language: "js",
      code: 'const cards = [\n  { id: 1, dependent: [6, 7, 8] },\n  { id: 2, dependent: [6] },\n  { id: 3, dependent: [] },\n  { id: 4, dependent: [6, 7, 8] },\n  { id: 5, dependent: [6, 8] },\n  { id: 6, dependent: [] },\n  { id: 7, dependent: [6] },\n  { id: 8, dependent: [7] },\n  { id: 9, dependent: [1] },\n  { id: 10, dependent: [9] },\n];\n\nconst getOrderedCards = (cards) => {\n  const result = [];\n  const added = new Set();\n\n  while (result.length < cards.length) {\n    let addedInPass = false;\n\n    for (const card of cards) {\n      if (\n        !added.has(card.id) &&\n        card.dependent.every((dep) => added.has(dep))\n      ) {\n        result.push(card.id);\n        added.add(card.id);\n        addedInPass = true;\n      }\n    }\n\n    if (!addedInPass) {\n      throw new Error("Cannot resolve dependency order");\n    }\n  }\n\n  return result;\n};\n\nconsole.log(getOrderedCards(cards));',
      createdAt: "2026-08-02T10:37:16.835Z",
      updatedAt: "2026-08-02T10:37:16.835Z",
    },
  ],
  meta: {
    total: 71,
    page: 1,
    limit: 100,
    totalPages: 1,
  },
};
